/* Generated by Nim Compiler v2.2.4 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -pthread   -I/usr/lib/nim/lib -I/home/luminary/Documents/Cybersecurite/Oteria/Venom/ssh_stealer -o /home/luminary/Documents/Cybersecurite/Oteria/Venom/ssh_stealer/sortie_c/@m..@s..@s..@s..@s..@s..@s..@susr@slib@snim@slib@sstd@sprivate@sosappdirs.nim.c.o /home/luminary/Documents/Cybersecurite/Oteria/Venom/ssh_stealer/sortie_c/@m..@s..@s..@s..@s..@s..@s..@susr@slib@snim@slib@sstd@sprivate@sosappdirs.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NimStringV2 tyArray__sMpvt1sOxOJ3LFGulnbeMQ[4];
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u2708)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, existsEnv__stdZenvvars_u20)(NimStringV2 key_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___system_u2714)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, getEnv__stdZenvvars_u15)(NimStringV2 key_p0, NimStringV2 default_p1);
static N_INLINE(void, eqdestroy___system_u281)(NimStringV2 x_p0);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4727)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, normalizePathEnd__stdZprivateZospaths2_u20)(NimStringV2* path_p0, NIM_BOOL trailingSep_p1);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__XnRPlAiwKKY6TokjvYVCvw_2 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__XnRPlAiwKKY6TokjvYVCvw_3 = {0, (NimStrPayload*)&TM__XnRPlAiwKKY6TokjvYVCvw_2};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__XnRPlAiwKKY6TokjvYVCvw_5 = { 6 | NIM_STRLIT_FLAG, "TMPDIR" };
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__XnRPlAiwKKY6TokjvYVCvw_6 = { 4 | NIM_STRLIT_FLAG, "TEMP" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__XnRPlAiwKKY6TokjvYVCvw_7 = { 3 | NIM_STRLIT_FLAG, "TMP" };
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__XnRPlAiwKKY6TokjvYVCvw_8 = { 7 | NIM_STRLIT_FLAG, "TEMPDIR" };
static const NimStringV2 TM__XnRPlAiwKKY6TokjvYVCvw_9 = {0, (NimStrPayload*)&TM__XnRPlAiwKKY6TokjvYVCvw_2};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__XnRPlAiwKKY6TokjvYVCvw_10 = { 4 | NIM_STRLIT_FLAG, "/tmp" };
static const NimStringV2 TM__XnRPlAiwKKY6TokjvYVCvw_11 = {4, (NimStrPayload*)&TM__XnRPlAiwKKY6TokjvYVCvw_10};
static NIM_CONST tyArray__sMpvt1sOxOJ3LFGulnbeMQ TM__XnRPlAiwKKY6TokjvYVCvw_4 = {{6, (NimStrPayload*)&TM__XnRPlAiwKKY6TokjvYVCvw_5},
{4, (NimStrPayload*)&TM__XnRPlAiwKKY6TokjvYVCvw_6},
{3, (NimStrPayload*)&TM__XnRPlAiwKKY6TokjvYVCvw_7},
{7, (NimStrPayload*)&TM__XnRPlAiwKKY6TokjvYVCvw_8}}
;
extern NIM_THREADVAR TFrame* framePtr__system_u2741;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4509;
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2741 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2741).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2741;
	framePtr__system_u2741 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4727();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2741 = (*framePtr__system_u2741).prev;
}
static N_INLINE(void, eqdestroy___system_u281)(NimStringV2 x_p0) {
	nimfr_("=destroy", "/usr/lib/nim/lib/system.nim");
	popFrame();
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4509);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosgetTempDir)(void) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("getTempDir", "/usr/lib/nim/lib/std/private/osappdirs.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(161, "/usr/lib/nim/lib/std/private/osappdirs.nim");	result = TM__XnRPlAiwKKY6TokjvYVCvw_3;
	{
		NimStringV2 dirX60gensym3__1;
		NI i_1;
		dirX60gensym3__1.len = 0; dirX60gensym3__1.p = NIM_NIL;
		nimlf_(43, "/usr/lib/nim/lib/system/iterators.nim");		i_1 = ((NI)0);
		{
			nimln_(44);			while (1) {
				nimlf_(1694, "/usr/lib/nim/lib/system.nim");				eqcopy___system_u2708((&dirX60gensym3__1), TM__XnRPlAiwKKY6TokjvYVCvw_4[(i_1)- 0]);
				nimlf_(126, "/usr/lib/nim/lib/std/private/osappdirs.nim");				{
					NIM_BOOL T7_;
					NimStringV2 T10_;
					T7_ = (NIM_BOOL)0;
					T7_ = existsEnv__stdZenvvars_u20(dirX60gensym3__1);
					if (NIM_UNLIKELY(*nimErr_)) goto LA2_;
					if (!T7_) goto LA8_;
					nimlf_(1694, "/usr/lib/nim/lib/system.nim");					nimlf_(127, "/usr/lib/nim/lib/std/private/osappdirs.nim");					T10_.len = 0; T10_.p = NIM_NIL;
					T10_ = getEnv__stdZenvvars_u15(dirX60gensym3__1, TM__XnRPlAiwKKY6TokjvYVCvw_9);
					if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T10_); goto LA2_;}
					nimlf_(1694, "/usr/lib/nim/lib/system.nim");					eqsink___system_u2714((&result), T10_);
					nimln_(394);					if (dirX60gensym3__1.p && !(dirX60gensym3__1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(dirX60gensym3__1.p);
}
					nimlf_(128, "/usr/lib/nim/lib/std/private/osappdirs.nim");					goto LA1;
				}
LA8_: ;
				nimlf_(46, "/usr/lib/nim/lib/system/iterators.nim");				{
					if (!(((NI)3) <= i_1)) goto LA13_;
					goto LA3;
				}
LA13_: ;
				nimln_(13);				i_1 += ((NI)1);
			}
		} LA3: ;
		{
			LA2_:;
		}
		{
			nimlf_(394, "/usr/lib/nim/lib/system.nim");			if (dirX60gensym3__1.p && !(dirX60gensym3__1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(dirX60gensym3__1.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	} LA1: ;
	nimlf_(175, "/usr/lib/nim/lib/std/private/osappdirs.nim");	{
		if (!(result.len == ((NI)0))) goto LA19_;
		nimlf_(1694, "/usr/lib/nim/lib/system.nim");		eqsink___system_u2714((&result), TM__XnRPlAiwKKY6TokjvYVCvw_11);
	}
LA19_: ;
	nimlf_(177, "/usr/lib/nim/lib/std/private/osappdirs.nim");	normalizePathEnd__stdZprivateZospaths2_u20((&result), NIM_TRUE);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
