/* Generated by Nim Compiler v2.2.4 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -pthread   -I/usr/lib/nim/lib -I/home/luminary/Documents/Cybersecurite/Oteria/Venom/ssh_stealer -o /home/luminary/Documents/Cybersecurite/Oteria/Venom/ssh_stealer/sortie_c/@m..@s..@s..@s..@s..@s..@s..@susr@slib@snim@slib@spure@sos.nim.c.o /home/luminary/Documents/Cybersecurite/Oteria/Venom/ssh_stealer/sortie_c/@m..@s..@s..@s..@s..@s..@s..@susr@slib@snim@slib@spure@sos.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <sys/stat.h>
#include <sys/types.h>
#include <time.h>
#include <string.h>
#include <unistd.h>
#include <stdlib.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseOSError__stdZoserrors_u119)(NI32 errorCode_p0, NimStringV2 additionalInfo_p1);
N_LIB_PRIVATE N_NIMCALL(NI32, osLastError__stdZoserrors_u122)(void);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4727)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(int, exitStatusLikeShell__pureZos_u160)(int status_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, WIFSIGNALED__posixZposix_u1079)(int s_p0);
N_LIB_PRIVATE N_NIMCALL(int, WTERMSIG__posixZposix_u1070)(int s_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(int, WEXITSTATUS__posixZposix_u1063)(int s_p0);
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4509;
extern NIM_THREADVAR TFrame* framePtr__system_u2741;
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4509);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0) {
	NCSTRING result;
	{
		if (!(s_p0.len == ((NI)0))) goto LA3_;
		result = "";
	}
	goto LA1_;
LA3_: ;
	{
		result = ((NCSTRING) ((*s_p0.p).data));
	}
LA1_: ;
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2741 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2741).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2741;
	framePtr__system_u2741 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4727();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2741 = (*framePtr__system_u2741).prev;
}
N_LIB_PRIVATE N_NIMCALL(NI64, nosgetFileSize)(NimStringV2 file_p0) {
	NI64 result;
	struct stat rawInfo_1;
NIM_BOOL* nimErr_;
	nimfr_("getFileSize", "/usr/lib/nim/lib/pure/os.nim");
{nimErr_ = nimErrorFlag();
	result = (NI64)0;
	nimlf_(459, "/usr/lib/nim/lib/pure/os.nim");	nimln_(468);	nimZeroMem((void*)(&rawInfo_1), sizeof(struct stat));
	nimln_(469);	{
		int T3_;
		NI32 T6_;
		T3_ = (int)0;
		T3_ = stat(nimToCStringConv(file_p0), (&rawInfo_1));
		if (!(T3_ < ((NI32)0))) goto LA4_;
		nimln_(470);		T6_ = (NI32)0;
		T6_ = osLastError__stdZoserrors_u122();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		raiseOSError__stdZoserrors_u119(T6_, file_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA4_: ;
	result = ((NI64) (rawInfo_1.st_size));
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, getCurrentProcessId__pureZos_u445)(void) {
	NI result;
	pid_t T1_;
	nimfr_("getCurrentProcessId", "/usr/lib/nim/lib/pure/os.nim");
	nimln_(954);	T1_ = (pid_t)0;
	T1_ = getpid();
	result = ((NI) (T1_));
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(int, exitStatusLikeShell__pureZos_u160)(int status_p0) {
	int result;
	NI32 colontmpD_;
	int colontmpD__2;
NIM_BOOL* nimErr_;
	nimfr_("exitStatusLikeShell", "/usr/lib/nim/lib/pure/os.nim");
{nimErr_ = nimErrorFlag();
	result = (int)0;
	colontmpD_ = (NI32)0;
	colontmpD__2 = (int)0;
	nimln_(474);	nimln_(476);	{
		NIM_BOOL T3_;
		int T6_;
		NI TM__yu6cxgKBBXbNsTkT9cyMd4g_2;
		T3_ = (NIM_BOOL)0;
		T3_ = WIFSIGNALED__posixZposix_u1079(status_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!T3_) goto LA4_;
		nimln_(478);		T6_ = (int)0;
		T6_ = WTERMSIG__posixZposix_u1070(status_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (nimAddInt(((NI32)128), T6_, &TM__yu6cxgKBBXbNsTkT9cyMd4g_2)) { raiseOverflow(); goto BeforeRet_;
		};
		if (TM__yu6cxgKBBXbNsTkT9cyMd4g_2 < (-2147483647 -1) || TM__yu6cxgKBBXbNsTkT9cyMd4g_2 > 2147483647){ raiseOverflow(); goto BeforeRet_;
		}
		colontmpD_ = (NI32)(TM__yu6cxgKBBXbNsTkT9cyMd4g_2);
		result = colontmpD_;
	}
	goto LA1_;
LA4_: ;
	{
		nimln_(480);		colontmpD__2 = WEXITSTATUS__posixZposix_u1063(status_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		result = colontmpD__2;
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, nosexecShellCmd)(NimStringV2 command_p0) {
	NI result;
	int T1_;
	int T2_;
NIM_BOOL* nimErr_;
	nimfr_("execShellCmd", "/usr/lib/nim/lib/pure/os.nim");
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	nimln_(500);	T1_ = (int)0;
	T1_ = system(nimToCStringConv(command_p0));
	T2_ = (int)0;
	T2_ = exitStatusLikeShell__pureZos_u160(T1_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = ((NI) (T2_));
	}BeforeRet_: ;
	popFrame();
	return result;
}
