/* Generated by Nim Compiler v2.2.4 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -pthread   -I/usr/lib/nim/lib -I/home/luminary/Documents/Cybersecurite/Oteria/Venom/ssh_stealer -o /home/luminary/Documents/Cybersecurite/Oteria/Venom/ssh_stealer/sortie_c/@m..@s..@s..@s..@s..@s..@s..@susr@slib@snim@slib@sstd@scmdline.nim.c.o /home/luminary/Documents/Cybersecurite/Oteria/Venom/ssh_stealer/sortie_c/@m..@s..@s..@s..@s..@s..@s..@susr@slib@snim@slib@sstd@scmdline.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
extern int cmdCount;
extern NCSTRING* cmdLine;
