/* Generated by Nim Compiler v2.2.4 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -pthread   -I/usr/lib/nim/lib -I/home/luminary/Documents/Cybersecurite/Oteria/Venom/ssh_stealer -o /home/luminary/Documents/Cybersecurite/Oteria/Venom/ssh_stealer/sortie_c/@m..@s..@s..@s..@s..@s..@s..@susr@slib@snim@slib@sstd@ssyncio.nim.c.o /home/luminary/Documents/Cybersecurite/Oteria/Venom/ssh_stealer/sortie_c/@m..@s..@s..@s..@s..@s..@s..@susr@slib@snim@slib@sstd@ssyncio.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdio.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <fcntl.h>
#include <string.h>
#include <errno.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_IOError__Vn1F4tzy8Snk2yXd61F9cQA tyObject_IOError__Vn1F4tzy8Snk2yXd61F9cQA;
typedef struct tyObject_CatchableError__9ab9cPq83jNmwEkPYefdrBpg tyObject_CatchableError__9ab9cPq83jNmwEkPYefdrBpg;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ;
typedef struct tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ_Content tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ_Content;
typedef struct tyObject_StackTraceEntry__Ys9cmA3ckZAVfrZgZt9axXEw tyObject_StackTraceEntry__Ys9cmA3ckZAVfrZgZt9axXEw;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NU8 tyEnum_FileMode__BzUbNzIgtuxKp78IxN69cmQ;
typedef NCSTRING tyArray__nq9cbEx9ban2S9bymlRtG7G2w[5];
typedef NIM_CHAR tyArray__PbS9a6gkxCuxWEnFq4lOU9aw[24];
typedef NIM_CHAR tyArray__hToc9cajraNwyrQdTvLCS3A[116];
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ {
  NI len; tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ trace;
	Exception* up;
};
struct tyObject_CatchableError__9ab9cPq83jNmwEkPYefdrBpg {
	Exception Sup;
};
struct tyObject_IOError__Vn1F4tzy8Snk2yXd61F9cQA {
	tyObject_CatchableError__9ab9cPq83jNmwEkPYefdrBpg Sup;
};
struct tyObject_StackTraceEntry__Ys9cmA3ckZAVfrZgZt9axXEw {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ_Content { NI cap; tyObject_StackTraceEntry__Ys9cmA3ckZAVfrZgZt9axXEw data[SEQ_DECL_SIZE]; };
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NIMCALL(int, getFileHandle__stdZsyncio_u279)(FILE* f_p0);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4727)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, modeIsDir__stdZsyncio_u408)(mode_t m_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, checkErr__stdZsyncio_u162)(FILE* f_p0);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1731)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u29)(NI32 xX60gensym3__p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, cstrToNimstr)(NCSTRING str_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseEIO__stdZsyncio_u92)(NimStringV2 msg_p0);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, eqdup___system_u2711)(NimStringV2 src_p0);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e_p0, NCSTRING ename_p1, NCSTRING procname_p2, NCSTRING filename_p3, NI line_p4);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, open__stdZsyncio_u414)(FILE** f_p0, NimStringV2 filename_p1, tyEnum_FileMode__BzUbNzIgtuxKp78IxN69cmQ mode_p2, NI bufSize_p3);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, readAll__stdZsyncio_u380)(FILE* file_p0);
N_LIB_PRIVATE N_NIMCALL(NI64, rawFileSize__stdZsyncio_u363)(FILE* file_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, readAllFile__stdZsyncio_u371)(FILE* file_p0, NI64 len_p1);
N_NIMCALL(NimStringV2, mnewString)(NI len_p0);
N_LIB_PRIVATE N_NIMCALL(NI, readBuffer__stdZsyncio_u165)(FILE* f_p0, void* buffer_p1, NI len_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, endOfFile__stdZsyncio_u367)(FILE* f_p0);
N_LIB_PRIVATE N_NIMCALL(void, setLengthStrV2)(NimStringV2* s_p0, NI newLen_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, readAllBuffer__stdZsyncio_u358)(FILE* file_p0);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s_p0, NI addLen_p1);
N_LIB_PRIVATE N_NIMCALL(void, close__stdZsyncio_u268)(FILE* f_p0);
N_LIB_PRIVATE N_NIMCALL(void, write__stdZsyncio_u254)(FILE* f_p0, NimStringV2 s_p1);
N_LIB_PRIVATE N_NIMCALL(NI, writeBuffer__stdZsyncio_u196)(FILE* f_p0, void* buffer_p1, NI len_p2);
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_2 = { 7 | NIM_STRLIT_FLAG, "errno: " };
static const NimStringV2 TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_3 = {7, (NimStrPayload*)&TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_2};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_5 = { 2 | NIM_STRLIT_FLAG, " `" };
static const NimStringV2 TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_6 = {2, (NimStrPayload*)&TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_5};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_7 = { 1 | NIM_STRLIT_FLAG, "`" };
static const NimStringV2 TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_8 = {1, (NimStrPayload*)&TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_7};
extern TNimTypeV2 NTIv2__Vn1F4tzy8Snk2yXd61F9cQA_;
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_9 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_10 = {0, (NimStrPayload*)&TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_9};
static const struct {
  NI cap; NIM_CHAR data[13+1];
} TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_11 = { 13 | NIM_STRLIT_FLAG, "cannot open: " };
static const NimStringV2 TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_12 = {13, (NimStrPayload*)&TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_11};
static const struct {
  NI cap; NIM_CHAR data[27+1];
} TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_13 = { 27 | NIM_STRLIT_FLAG, "cannot write string to file" };
static const NimStringV2 TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_14 = {27, (NimStrPayload*)&TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_13};
static const NimStringV2 TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_15 = {13, (NimStrPayload*)&TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_11};
static const NimStringV2 TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_16 = {13, (NimStrPayload*)&TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_11};
N_LIB_PRIVATE NIM_CONST tyArray__nq9cbEx9ban2S9bymlRtG7G2w FormatOpen__stdZsyncio_u402 = {"rbe",
"wbe",
"w+be",
"r+be",
"abe"}
;
extern NIM_THREADVAR TFrame* framePtr__system_u2741;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4509;
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0) {
	NCSTRING result;
	{
		if (!(s_p0.len == ((NI)0))) goto LA3_;
		result = "";
	}
	goto LA1_;
LA3_: ;
	{
		result = ((NCSTRING) ((*s_p0.p).data));
	}
LA1_: ;
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2741 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2741).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2741;
	framePtr__system_u2741 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4727();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2741 = (*framePtr__system_u2741).prev;
}
N_LIB_PRIVATE N_NIMCALL(int, getFileHandle__stdZsyncio_u279)(FILE* f_p0) {
	int result;
	nimfr_("getFileHandle", "/usr/lib/nim/lib/std/syncio.nim");
	nimlf_(359, "/usr/lib/nim/lib/std/syncio.nim");	nimln_(364);	result = fileno(f_p0);
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, modeIsDir__stdZsyncio_u408)(mode_t m_p0) {
	NIM_BOOL result;
	nimfr_("modeIsDir", "/usr/lib/nim/lib/std/syncio.nim");
	nimln_(691);	nimln_(692);	result = ((NI32)(m_p0 & ((NI32)61440)) == ((NI32)16384));
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4509);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, open__stdZsyncio_u414)(FILE** f_p0, NimStringV2 filename_p1, tyEnum_FileMode__BzUbNzIgtuxKp78IxN69cmQ mode_p2, NI bufSize_p3) {
	NIM_BOOL result;
	void* p_1;
NIM_BOOL* nimErr_;
	nimfr_("open", "/usr/lib/nim/lib/std/syncio.nim");
{nimErr_ = nimErrorFlag();
	nimln_(718);	p_1 = fopen(nimToCStringConv(filename_p1), FormatOpen__stdZsyncio_u402[(mode_p2)- 0]);
	nimln_(719);	{
		FILE* f2_1;
		struct stat res_1;
		if (!!((p_1 == NIM_NIL))) goto LA3_;
		nimln_(720);		f2_1 = ((FILE*) (p_1));
		nimln_(726);		{
			NIM_BOOL T7_;
			int T8_;
			int T9_;
			T7_ = (NIM_BOOL)0;
			T8_ = (int)0;
			T8_ = getFileHandle__stdZsyncio_u279(f2_1);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			T9_ = (int)0;
			T9_ = fstat(T8_, (&res_1));
			T7_ = (((NI32)0) <= T9_);
			if (!(T7_)) goto LA10_;
			T7_ = modeIsDir__stdZsyncio_u408(res_1.st_mode);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
LA10_: ;
			if (!T7_) goto LA11_;
			nimln_(727);			{
				int T17_;
				nimln_(327);				if (!!((f2_1 == 0))) goto LA15_;
				nimln_(328);				T17_ = (int)0;
				T17_ = fclose(f2_1);
				(void)(T17_);
			}
LA15_: ;
			nimln_(728);			nimln_(709);			nimln_(728);			result = NIM_FALSE;
			goto BeforeRet_;
		}
LA11_: ;
		nimln_(735);		result = NIM_TRUE;
		nimln_(736);		(*f_p0) = ((FILE*) (p_1));
		nimln_(737);		{
			NIM_BOOL T20_;
			int T24_;
			T20_ = (NIM_BOOL)0;
			T20_ = (((NI)0) < bufSize_p3);
			if (!(T20_)) goto LA21_;
			T20_ = ((NU64)(((NU) (bufSize_p3))) <= (NU64)(((NU)-1)));
LA21_: ;
			if (!T20_) goto LA22_;
			nimln_(738);			T24_ = (int)0;
			T24_ = setvbuf((*f_p0), NIM_NIL, _IOFBF, ((size_t) (bufSize_p3)));
			(void)(T24_);
		}
		goto LA18_;
LA22_: ;
		{
			int T28_;
			nimln_(739);			if (!(bufSize_p3 == ((NI)0))) goto LA26_;
			nimln_(740);			T28_ = (int)0;
			T28_ = setvbuf((*f_p0), NIM_NIL, _IONBF, ((size_t)0));
			(void)(T28_);
		}
		goto LA18_;
LA26_: ;
LA18_: ;
	}
	goto LA1_;
LA3_: ;
	{
		nimln_(742);		result = NIM_FALSE;
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, close__stdZsyncio_u268)(FILE* f_p0) {
	nimfr_("close", "/usr/lib/nim/lib/std/syncio.nim");
	nimln_(343);	{
		int T5_;
		nimln_(327);		if (!!((f_p0 == 0))) goto LA3_;
		nimln_(328);		T5_ = (int)0;
		T5_ = fclose(f_p0);
		(void)(T5_);
	}
LA3_: ;
	popFrame();
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1731)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
{	{
		NI TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_4;
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		if ((src_p1.len) < ((NI)0) || (src_p1.len) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(src_p1.len, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		copyMem__system_u1731(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		if (nimAddInt((*dest_p0).len, src_p1.len, &TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_4)) { raiseOverflow(); goto BeforeRet_;
		};
		(*dest_p0).len = (NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_4);
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NOINLINE(void, raiseEIO__stdZsyncio_u92)(NimStringV2 msg_p0) {
	NimStringV2 colontmpD_;
	tyObject_IOError__Vn1F4tzy8Snk2yXd61F9cQA* T1_;
	nimfr_("raiseEIO", "/usr/lib/nim/lib/std/syncio.nim");
{	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	T1_ = NIM_NIL;
	T1_ = (tyObject_IOError__Vn1F4tzy8Snk2yXd61F9cQA*) nimNewObj(sizeof(tyObject_IOError__Vn1F4tzy8Snk2yXd61F9cQA), NIM_ALIGNOF(tyObject_IOError__Vn1F4tzy8Snk2yXd61F9cQA));
	(*T1_).Sup.Sup.Sup.m_type = (&NTIv2__Vn1F4tzy8Snk2yXd61F9cQA_);
	(*T1_).Sup.Sup.name = "IOError";
	nimln_(157);	nimlf_(1694, "/usr/lib/nim/lib/system.nim");	colontmpD_ = eqdup___system_u2711(msg_p0);
	(*T1_).Sup.Sup.message = colontmpD_;
	(*T1_).Sup.Sup.parent = ((Exception*) NIM_NIL);
	nimlf_(157, "/usr/lib/nim/lib/std/syncio.nim");	raiseExceptionEx((Exception*)T1_, "IOError", "raiseEIO", "/usr/lib/nim/lib/std/syncio.nim", 157);
goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, checkErr__stdZsyncio_u162)(FILE* f_p0) {
NIM_BOOL* nimErr_;
	nimfr_("checkErr", "/usr/lib/nim/lib/std/syncio.nim");
{nimErr_ = nimErrorFlag();
	nimln_(171);	{
		int T3_;
		NimStringV2 msg_1;
		NimStringV2 colontmpD_;
		NimStringV2 colontmpD__2;
		NimStringV2 T7_;
		NCSTRING T8_;
		T3_ = (int)0;
		T3_ = ferror(f_p0);
		if (!!((T3_ == ((NI32)0)))) goto LA4_;
		msg_1.len = 0; msg_1.p = NIM_NIL;
		colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
		colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
		nimln_(172);		T7_.len = 0; T7_.p = NIM_NIL;
		colontmpD_ = dollar___systemZdollars_u29(errno);
		if (NIM_UNLIKELY(*nimErr_)) goto LA6_;
		T8_ = (NCSTRING)0;
		T8_ = strerror(errno);
		colontmpD__2 = cstrToNimstr(T8_);
		T7_ = rawNewString(colontmpD_.len + colontmpD__2.len + 10);
appendString((&T7_), TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_3);
appendString((&T7_), colontmpD_);
appendString((&T7_), TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_6);
appendString((&T7_), colontmpD__2);
appendString((&T7_), TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_8);
		msg_1 = T7_;
		nimln_(173);		clearerr(f_p0);
		nimln_(174);		raiseEIO__stdZsyncio_u92(msg_1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA6_;
		{
			LA6_:;
		}
		{
			nimlf_(394, "/usr/lib/nim/lib/system.nim");			if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
			if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
			if (msg_1.p && !(msg_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(msg_1.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA4_: ;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(NI, readBuffer__stdZsyncio_u165)(FILE* f_p0, void* buffer_p1, NI len_p2) {
	NI result;
	size_t T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	T1_ = (size_t)0;
	T1_ = fread(buffer_p1, ((size_t)1), ((size_t) (len_p2)), f_p0);
	result = ((NI) (T1_));
	{
		if (!!((result == len_p2))) goto LA4_;
		checkErr__stdZsyncio_u162(f_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA4_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, writeBuffer__stdZsyncio_u196)(FILE* f_p0, void* buffer_p1, NI len_p2) {
	NI result;
	size_t T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	T1_ = (size_t)0;
	T1_ = fwrite(buffer_p1, ((size_t)1), ((size_t) (len_p2)), f_p0);
	result = ((NI) (T1_));
	checkErr__stdZsyncio_u162(f_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, flushFile__stdZsyncio_u277)(FILE* f_p0) {
	int T1_;
	nimfr_("flushFile", "/usr/lib/nim/lib/std/syncio.nim");
	nimlf_(356, "/usr/lib/nim/lib/std/syncio.nim");	T1_ = (int)0;
	T1_ = fflush(f_p0);
	(void)(T1_);
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(NI64, rawFileSize__stdZsyncio_u363)(FILE* file_p0) {
	NI64 result;
	NI64 oldPos_1;
	int T1_;
	int T2_;
	nimfr_("rawFileSize", "/usr/lib/nim/lib/std/syncio.nim");
	nimln_(572);	oldPos_1 = ftello(file_p0);
	nimln_(573);	T1_ = (int)0;
	T1_ = fseeko(file_p0, IL64(0), ((int)2));
	(void)(T1_);
	nimln_(574);	result = ftello(file_p0);
	nimln_(575);	T2_ = (int)0;
	T2_ = fseeko(file_p0, oldPos_1, ((int)0));
	(void)(T2_);
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, endOfFile__stdZsyncio_u367)(FILE* f_p0) {
	NIM_BOOL result;
	int c_1;
	int T1_;
	nimfr_("endOfFile", "/usr/lib/nim/lib/std/syncio.nim");
{	nimln_(579);	c_1 = fgetc(f_p0);
	nimln_(580);	T1_ = (int)0;
	T1_ = ungetc(c_1, f_p0);
	(void)(T1_);
	nimln_(581);	nimln_(577);	nimln_(581);	result = (c_1 < ((NI32)0));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, readAllBuffer__stdZsyncio_u358)(FILE* file_p0) {
	NimStringV2 result;
	NimStringV2 buffer_1;
NIM_BOOL* nimErr_;
	nimfr_("readAllBuffer", "/usr/lib/nim/lib/std/syncio.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	buffer_1.len = 0; buffer_1.p = NIM_NIL;
	nimln_(559);	result = TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_10;
	nimln_(560);	buffer_1 = mnewString(((NI)4000));
	{
		nimln_(561);		while (1) {
			NI bytesRead_1;
			nimln_(562);			if (((NI)0) < 0 || ((NI)0) >= buffer_1.len){ raiseIndexError2(((NI)0),buffer_1.len-1); goto LA1_;
			}
			bytesRead_1 = readBuffer__stdZsyncio_u165(file_p0, ((void*) ((&buffer_1.p->data[((NI)0)]))), ((NI)4000));
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
			nimln_(563);			{
				if (!(bytesRead_1 == ((NI)4000))) goto LA6_;
				nimln_(564);				prepareAdd((&result), buffer_1.len + 0);
appendString((&result), buffer_1);
			}
			goto LA4_;
LA6_: ;
			{
				nimln_(566);				if ((bytesRead_1) < ((NI)0) || (bytesRead_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(bytesRead_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto LA1_;
				}
				setLengthStrV2((&buffer_1), (bytesRead_1));
				nimln_(567);				prepareAdd((&result), buffer_1.len + 0);
appendString((&result), buffer_1);
				nimln_(568);				goto LA2;
			}
LA4_: ;
		}
	} LA2: ;
	{
		LA1_:;
	}
	{
		nimlf_(394, "/usr/lib/nim/lib/system.nim");		if (buffer_1.p && !(buffer_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(buffer_1.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, readAllFile__stdZsyncio_u371)(FILE* file_p0, NI64 len_p1) {
	NimStringV2 result;
	NI bytes_1;
NIM_BOOL* nimErr_;
	nimfr_("readAllFile", "/usr/lib/nim/lib/std/syncio.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimlf_(587, "/usr/lib/nim/lib/std/syncio.nim");	if ((len_p1) < ((NI)0) || (len_p1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(len_p1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	result = mnewString(((NI) (len_p1)));
	nimln_(588);	if (((NI)0) < 0 || ((NI)0) >= result.len){ raiseIndexError2(((NI)0),result.len-1); goto BeforeRet_;
	}
	if ((len_p1) < ((NI)0) || (len_p1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(len_p1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	bytes_1 = readBuffer__stdZsyncio_u165(file_p0, ((void*) ((&result.p->data[((NI)0)]))), ((NI) (len_p1)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(589);	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = endOfFile__stdZsyncio_u367(file_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!T3_) goto LA4_;
		nimln_(590);		{
			if (!(((NI64) (bytes_1)) < len_p1)) goto LA8_;
			nimln_(591);			if ((bytes_1) < ((NI)0) || (bytes_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(bytes_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
			}
			setLengthStrV2((&result), (bytes_1));
		}
LA8_: ;
	}
	goto LA1_;
LA4_: ;
	{
		NimStringV2 colontmpD_;
		colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
		nimln_(595);		colontmpD_ = readAllBuffer__stdZsyncio_u358(file_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto LA11_;
		prepareAdd((&result), colontmpD_.len + 0);
appendString((&result), colontmpD_);
		{
			LA11_:;
		}
		{
			nimlf_(394, "/usr/lib/nim/lib/system.nim");			if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, readAll__stdZsyncio_u380)(FILE* file_p0) {
	NimStringV2 result;
	NI64 colontmpD_;
	NI64 colontmpD__2;
	NI64 len_1;
NIM_BOOL* nimErr_;
	nimfr_("readAll", "/usr/lib/nim/lib/std/syncio.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	colontmpD_ = (NI64)0;
	colontmpD__2 = (NI64)0;
	nimlf_(610, "/usr/lib/nim/lib/std/syncio.nim");	{
		if (!!((file_p0 == stdin))) goto LA3_;
		colontmpD_ = rawFileSize__stdZsyncio_u363(file_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		len_1 = colontmpD_;
	}
	goto LA1_;
LA3_: ;
	{
		colontmpD__2 = IL64(-1);
		len_1 = colontmpD__2;
	}
LA1_: ;
	nimln_(613);	{
		if (!(IL64(0) < len_1)) goto LA8_;
		nimln_(614);		result = readAllFile__stdZsyncio_u371(file_p0, len_1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA6_;
LA8_: ;
	{
		nimln_(616);		result = readAllBuffer__stdZsyncio_u358(file_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA6_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, readFile__stdZsyncio_u529)(NimStringV2 filename_p0) {
	NimStringV2 result;
	FILE* f_1;
NIM_BOOL oldNimErrFin6_;
NIM_BOOL* nimErr_;
	nimfr_("readFile", "/usr/lib/nim/lib/std/syncio.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimln_(869);	f_1 = ((FILE*) NIM_NIL);
	nimln_(870);	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = open__stdZsyncio_u414(&f_1, filename_p0, ((tyEnum_FileMode__BzUbNzIgtuxKp78IxN69cmQ)0), ((NI)-1));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!T3_) goto LA4_;
		nimln_(872);		result = readAll__stdZsyncio_u380(f_1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA6_;
		{
			LA6_:;
		}
		{
			oldNimErrFin6_ = *nimErr_; *nimErr_ = NIM_FALSE;
			nimln_(874);			close__stdZsyncio_u268(f_1);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			*nimErr_ = oldNimErrFin6_;
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
LA4_: ;
	{
		tyObject_IOError__Vn1F4tzy8Snk2yXd61F9cQA* T10_;
		NimStringV2 T11_;
		T10_ = NIM_NIL;
		T10_ = (tyObject_IOError__Vn1F4tzy8Snk2yXd61F9cQA*) nimNewObj(sizeof(tyObject_IOError__Vn1F4tzy8Snk2yXd61F9cQA), NIM_ALIGNOF(tyObject_IOError__Vn1F4tzy8Snk2yXd61F9cQA));
		(*T10_).Sup.Sup.Sup.m_type = (&NTIv2__Vn1F4tzy8Snk2yXd61F9cQA_);
		(*T10_).Sup.Sup.name = "IOError";
		nimln_(876);		T11_.len = 0; T11_.p = NIM_NIL;
		T11_ = rawNewString(filename_p0.len + 13);
appendString((&T11_), TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_12);
appendString((&T11_), filename_p0);
		(*T10_).Sup.Sup.message = T11_;
		(*T10_).Sup.Sup.parent = ((Exception*) NIM_NIL);
		raiseExceptionEx((Exception*)T10_, "IOError", "readFile", "/usr/lib/nim/lib/std/syncio.nim", 876);
goto BeforeRet_;
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, write__stdZsyncio_u254)(FILE* f_p0, NimStringV2 s_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		NI T3_;
		if ((s_p1.len) < ((NI)0) || (s_p1.len) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(s_p1.len, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		T3_ = (NI)0;
		T3_ = writeBuffer__stdZsyncio_u196(f_p0, ((void*) (nimToCStringConv(s_p1))), (s_p1.len));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!!((T3_ == s_p1.len))) goto LA4_;
		raiseEIO__stdZsyncio_u92(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_14);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA4_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, writeFile__stdZsyncio_u534)(NimStringV2 filename_p0, NimStringV2 content_p1) {
	FILE* f_1;
NIM_BOOL oldNimErrFin6_;
NIM_BOOL* nimErr_;
	nimfr_("writeFile", "/usr/lib/nim/lib/std/syncio.nim");
{nimErr_ = nimErrorFlag();
	nimln_(882);	f_1 = ((FILE*) NIM_NIL);
	nimln_(883);	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = open__stdZsyncio_u414(&f_1, filename_p0, ((tyEnum_FileMode__BzUbNzIgtuxKp78IxN69cmQ)1), ((NI)-1));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!T3_) goto LA4_;
		nimln_(885);		write__stdZsyncio_u254(f_1, content_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA6_;
		{
			LA6_:;
		}
		{
			oldNimErrFin6_ = *nimErr_; *nimErr_ = NIM_FALSE;
			nimln_(887);			close__stdZsyncio_u268(f_1);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			*nimErr_ = oldNimErrFin6_;
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
LA4_: ;
	{
		tyObject_IOError__Vn1F4tzy8Snk2yXd61F9cQA* T10_;
		NimStringV2 T11_;
		T10_ = NIM_NIL;
		T10_ = (tyObject_IOError__Vn1F4tzy8Snk2yXd61F9cQA*) nimNewObj(sizeof(tyObject_IOError__Vn1F4tzy8Snk2yXd61F9cQA), NIM_ALIGNOF(tyObject_IOError__Vn1F4tzy8Snk2yXd61F9cQA));
		(*T10_).Sup.Sup.Sup.m_type = (&NTIv2__Vn1F4tzy8Snk2yXd61F9cQA_);
		(*T10_).Sup.Sup.name = "IOError";
		nimln_(889);		T11_.len = 0; T11_.p = NIM_NIL;
		T11_ = rawNewString(filename_p0.len + 13);
appendString((&T11_), TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_15);
appendString((&T11_), filename_p0);
		(*T10_).Sup.Sup.message = T11_;
		(*T10_).Sup.Sup.parent = ((Exception*) NIM_NIL);
		raiseExceptionEx((Exception*)T10_, "IOError", "writeFile", "/usr/lib/nim/lib/std/syncio.nim", 889);
goto BeforeRet_;
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(FILE*, open__stdZsyncio_u487)(NimStringV2 filename_p0, tyEnum_FileMode__BzUbNzIgtuxKp78IxN69cmQ mode_p1, NI bufSize_p2) {
	FILE* result;
NIM_BOOL* nimErr_;
	nimfr_("open", "/usr/lib/nim/lib/std/syncio.nim");
{nimErr_ = nimErrorFlag();
	nimln_(786);	result = 0;
	nimln_(787);	{
		NIM_BOOL T3_;
		tyObject_IOError__Vn1F4tzy8Snk2yXd61F9cQA* T6_;
		NimStringV2 T7_;
		T3_ = (NIM_BOOL)0;
		T3_ = open__stdZsyncio_u414(&result, filename_p0, mode_p1, bufSize_p2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!!(T3_)) goto LA4_;
		T6_ = NIM_NIL;
		T6_ = (tyObject_IOError__Vn1F4tzy8Snk2yXd61F9cQA*) nimNewObj(sizeof(tyObject_IOError__Vn1F4tzy8Snk2yXd61F9cQA), NIM_ALIGNOF(tyObject_IOError__Vn1F4tzy8Snk2yXd61F9cQA));
		(*T6_).Sup.Sup.Sup.m_type = (&NTIv2__Vn1F4tzy8Snk2yXd61F9cQA_);
		(*T6_).Sup.Sup.name = "IOError";
		nimln_(788);		T7_.len = 0; T7_.p = NIM_NIL;
		T7_ = rawNewString(filename_p0.len + 13);
appendString((&T7_), TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_16);
appendString((&T7_), filename_p0);
		(*T6_).Sup.Sup.message = T7_;
		(*T6_).Sup.Sup.parent = ((Exception*) NIM_NIL);
		raiseExceptionEx((Exception*)T6_, "IOError", "open", "/usr/lib/nim/lib/std/syncio.nim", 788);
goto BeforeRet_;
	}
LA4_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
