/* Generated by Nim Compiler v2.2.4 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -pthread   -I/usr/lib/nim/lib -I/home/luminary/Documents/Cybersecurite/Oteria/Venom/ssh_stealer -o /home/luminary/Documents/Cybersecurite/Oteria/Venom/ssh_stealer/sortie_c/@m..@s..@s..@s..@s..@s..@s..@susr@slib@snim@slib@spure@smath.nim.c.o /home/luminary/Documents/Cybersecurite/Oteria/Venom/ssh_stealer/sortie_c/@m..@s..@s..@s..@s..@s..@s..@susr@slib@snim@slib@spure@smath.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
N_LIB_PRIVATE N_NIMCALL(NI64, floorDiv__pureZtimes_u304)(NI64 x_p0, NI64 y_p1) {
	NI64 result;
	NI64 r_1;
	result = (NI64)(x_p0 / y_p1);
	r_1 = (NI64)(x_p0 % y_p1);
	{
		NIM_BOOL T3_;
		NIM_BOOL T4_;
		NIM_BOOL T7_;
		T3_ = (NIM_BOOL)0;
		T4_ = (NIM_BOOL)0;
		T4_ = (IL64(0) < r_1);
		if (!(T4_)) goto LA5_;
		T4_ = (y_p1 < IL64(0));
LA5_: ;
		T3_ = T4_;
		if (T3_) goto LA6_;
		T7_ = (NIM_BOOL)0;
		T7_ = (r_1 < IL64(0));
		if (!(T7_)) goto LA8_;
		T7_ = (IL64(0) < y_p1);
LA8_: ;
		T3_ = T7_;
LA6_: ;
		if (!T3_) goto LA9_;
		result -= ((NI)1);
	}
LA9_: ;
	return result;
}
