/* Generated by Nim Compiler v2.2.4 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -pthread   -I/usr/lib/nim/lib -I/home/luminary/Documents/Cybersecurite/Oteria/Venom/ssh_stealer -o /home/luminary/Documents/Cybersecurite/Oteria/Venom/ssh_stealer/sortie_c/@m..@s..@s..@s..@s..@s..@s..@susr@slib@snim@slib@sstd@sprivate@sosfiles.nim.c.o /home/luminary/Documents/Cybersecurite/Oteria/Venom/ssh_stealer/sortie_c/@m..@s..@s..@s..@s..@s..@s..@susr@slib@snim@slib@sstd@sprivate@sosfiles.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <fcntl.h>
#include <unistd.h>
#include <errno.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NU8 tySet_tyEnum_CopyFlag__2lu8VnKKuY6xPpxEv7YWvA;
typedef NU8 tyEnum_CopyFlag__2lu8VnKKuY6xPpxEv7YWvA;
typedef NU8 tyEnum_FileMode__BzUbNzIgtuxKp78IxN69cmQ;
static N_INLINE(NI, countBits32)(NU32 n_p0);
static N_INLINE(NI, countSetBitsImpl__systemZcountbits95impl_u26)(NU32 x_p0);
N_CDECL(int, __builtin_popcount)(unsigned int x_p0);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4727)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u234)(NimStringV2 msg_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nossymlinkExists)(NimStringV2 link_p0);
N_LIB_PRIVATE N_NIMCALL(void, createSymlink__stdZprivateZossymlinks_u10)(NimStringV2 src_p0, NimStringV2 dest_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, expandSymlink__stdZprivateZossymlinks_u16)(NimStringV2 symlinkPath_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, open__stdZsyncio_u414)(FILE** f_p0, NimStringV2 filename_p1, tyEnum_FileMode__BzUbNzIgtuxKp78IxN69cmQ mode_p2, NI bufSize_p3);
N_LIB_PRIVATE N_NOINLINE(void, raiseOSError__stdZoserrors_u119)(NI32 errorCode_p0, NimStringV2 additionalInfo_p1);
N_LIB_PRIVATE N_NIMCALL(NI32, osLastError__stdZoserrors_u122)(void);
N_LIB_PRIVATE N_NIMCALL(void, close__stdZsyncio_u268)(FILE* f_p0);
N_LIB_PRIVATE N_NIMCALL(int, getFileHandle__stdZsyncio_u279)(FILE* f_p0);
N_LIB_PRIVATE N_NOCONV(void*, allocImpl__system_u1747)(NI size_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NIMCALL(NI, readBuffer__stdZsyncio_u165)(FILE* f_p0, void* buffer_p1, NI len_p2);
N_LIB_PRIVATE N_NIMCALL(NI, writeBuffer__stdZsyncio_u196)(FILE* f_p0, void* buffer_p1, NI len_p2);
N_LIB_PRIVATE N_NOCONV(void, dealloc)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, flushFile__stdZsyncio_u277)(FILE* f_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nostryRemoveFile)(NimStringV2 file_p0);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0);
static const struct {
  NI cap; NIM_CHAR data[137+1];
} TM__CMIme9a8i2wZOUbxErcFpJA_2 = { 137 | NIM_STRLIT_FLAG, "/usr/lib/nim/lib/std/private/osfiles.nim(213, 3) `card(copyFlagSymlink * options) == 1` There should be exactly one cfSymlink* in options" };
static const NimStringV2 TM__CMIme9a8i2wZOUbxErcFpJA_3 = {137, (NimStrPayload*)&TM__CMIme9a8i2wZOUbxErcFpJA_2};
extern NIM_THREADVAR TFrame* framePtr__system_u2741;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4509;
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2741 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2741).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2741;
	framePtr__system_u2741 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4727();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2741 = (*framePtr__system_u2741).prev;
}
static N_INLINE(NI, countSetBitsImpl__systemZcountbits95impl_u26)(NU32 x_p0) {
	NI result;
	NU32 x_2;
	int T1_;
	nimfr_("countSetBitsImpl", "/usr/lib/nim/lib/system/countbits_impl.nim");
	result = (NI)0;
	nimlf_(67, "/usr/lib/nim/lib/system/countbits_impl.nim");	x_2 = x_p0;
	nimln_(72);	T1_ = (int)0;
	T1_ = __builtin_popcount(((unsigned int) (x_2)));
	result = ((NI) (T1_));
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4509);
	return result;
}
static N_INLINE(NI, countBits32)(NU32 n_p0) {
	NI result;
NIM_BOOL* nimErr_;
	nimfr_("countBits32", "/usr/lib/nim/lib/system/countbits_impl.nim");
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	nimln_(90);	result = countSetBitsImpl__systemZcountbits95impl_u26(n_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, noscopyFile)(NimStringV2 source_p0, NimStringV2 dest_p1, tySet_tyEnum_CopyFlag__2lu8VnKKuY6xPpxEv7YWvA options_p2, NI bufferSize_p3) {
	NIM_BOOL isSymlink_1;
NIM_BOOL* nimErr_;
	nimfr_("copyFile", "/usr/lib/nim/lib/std/private/osfiles.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(213, "/usr/lib/nim/lib/std/private/osfiles.nim");	{
		if (!!((countBits32((7 & options_p2)) == ((NI)1)))) goto LA3_;
		failedAssertImpl__stdZassertions_u234(TM__CMIme9a8i2wZOUbxErcFpJA_3);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA3_: ;
	nimln_(214);	isSymlink_1 = nossymlinkExists(source_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(215);	{
		NIM_BOOL T7_;
		NIM_BOOL T9_;
		T7_ = (NIM_BOOL)0;
		T7_ = isSymlink_1;
		if (!(T7_)) goto LA8_;
		T9_ = (NIM_BOOL)0;
		T9_ = ((options_p2 &((NU8)1<<((NU)((((tyEnum_CopyFlag__2lu8VnKKuY6xPpxEv7YWvA)2)))&7U)))!=0);
		if (T9_) goto LA10_;
		T9_ = NIM_FALSE;
LA10_: ;
		T7_ = T9_;
LA8_: ;
		if (!T7_) goto LA11_;
		nimln_(216);		goto BeforeRet_;
	}
LA11_: ;
	nimln_(223);	{
		NIM_BOOL T15_;
		NimStringV2 colontmpD_;
		T15_ = (NIM_BOOL)0;
		T15_ = isSymlink_1;
		if (!(T15_)) goto LA16_;
		T15_ = ((options_p2 &((NU8)1<<((NU)((((tyEnum_CopyFlag__2lu8VnKKuY6xPpxEv7YWvA)0)))&7U)))!=0);
LA16_: ;
		if (!T15_) goto LA17_;
		colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
		nimln_(224);		colontmpD_ = expandSymlink__stdZprivateZossymlinks_u16(source_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto LA19_;
		createSymlink__stdZprivateZossymlinks_u10(colontmpD_, dest_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA19_;
		{
			LA19_:;
		}
		{
			nimlf_(394, "/usr/lib/nim/lib/system.nim");			if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA13_;
LA17_: ;
	{
		FILE* d_1;
		FILE* s_1;
		int T35_;
		int T36_;
		int T37_;
		int T38_;
		void* buf_1;
		d_1 = (FILE*)0;
		s_1 = (FILE*)0;
		nimlf_(241, "/usr/lib/nim/lib/std/private/osfiles.nim");		{
			NIM_BOOL T25_;
			NI32 T28_;
			T25_ = (NIM_BOOL)0;
			T25_ = open__stdZsyncio_u414(&s_1, source_p0, ((tyEnum_FileMode__BzUbNzIgtuxKp78IxN69cmQ)0), ((NI)-1));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!!(T25_)) goto LA26_;
			T28_ = (NI32)0;
			T28_ = osLastError__stdZoserrors_u122();
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			raiseOSError__stdZoserrors_u119(T28_, source_p0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA26_: ;
		nimln_(242);		{
			NIM_BOOL T31_;
			NI32 T34_;
			T31_ = (NIM_BOOL)0;
			T31_ = open__stdZsyncio_u414(&d_1, dest_p1, ((tyEnum_FileMode__BzUbNzIgtuxKp78IxN69cmQ)1), ((NI)-1));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!!(T31_)) goto LA32_;
			nimln_(243);			close__stdZsyncio_u268(s_1);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(244);			T34_ = (NI32)0;
			T34_ = osLastError__stdZoserrors_u122();
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			raiseOSError__stdZoserrors_u119(T34_, dest_p1);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA32_: ;
		nimln_(249);		T35_ = (int)0;
		T35_ = getFileHandle__stdZsyncio_u279(d_1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		T36_ = (int)0;
		T36_ = posix_fadvise(T35_, ((NI)0), ((NI)0), ((int)2));
		(void)(T36_);
		nimln_(250);		T37_ = (int)0;
		T37_ = getFileHandle__stdZsyncio_u279(s_1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		T38_ = (int)0;
		T38_ = posix_fadvise(T37_, ((NI)0), ((NI)0), ((int)2));
		(void)(T38_);
		nimln_(252);		if ((bufferSize_p3) < ((NI)0) || (bufferSize_p3) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(bufferSize_p3, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		buf_1 = allocImpl__system_u1747((bufferSize_p3));
		{
			nimln_(253);			while (1) {
				NI bytesread_1;
				nimln_(254);				if ((bufferSize_p3) < ((NI)0) || (bufferSize_p3) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(bufferSize_p3, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
				}
				bytesread_1 = readBuffer__stdZsyncio_u165(s_1, buf_1, (bufferSize_p3));
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				nimln_(255);				{
					NI byteswritten_1;
					if (!(((NI)0) < bytesread_1)) goto LA43_;
					nimln_(256);					if ((bytesread_1) < ((NI)0) || (bytesread_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(bytesread_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
					}
					byteswritten_1 = writeBuffer__stdZsyncio_u196(d_1, buf_1, (bytesread_1));
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					nimln_(257);					{
						NI32 T49_;
						if (!!((bytesread_1 == byteswritten_1))) goto LA47_;
						nimln_(258);						dealloc(buf_1);
						nimln_(259);						close__stdZsyncio_u268(s_1);
						if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
						nimln_(260);						close__stdZsyncio_u268(d_1);
						if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
						nimln_(261);						T49_ = (NI32)0;
						T49_ = osLastError__stdZoserrors_u122();
						if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
						raiseOSError__stdZoserrors_u119(T49_, dest_p1);
						if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					}
LA47_: ;
				}
LA43_: ;
				nimln_(262);				{
					if (!!((bytesread_1 == bufferSize_p3))) goto LA52_;
					goto LA39;
				}
LA52_: ;
			}
		} LA39: ;
		nimln_(263);		dealloc(buf_1);
		nimln_(264);		close__stdZsyncio_u268(s_1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(265);		flushFile__stdZsyncio_u277(d_1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(266);		close__stdZsyncio_u268(d_1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA13_: ;
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0) {
	NCSTRING result;
	{
		if (!(s_p0.len == ((NI)0))) goto LA3_;
		result = "";
	}
	goto LA1_;
LA3_: ;
	{
		result = ((NCSTRING) ((*s_p0.p).data));
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nostryRemoveFile)(NimStringV2 file_p0) {
	NIM_BOOL result;
	nimfr_("tryRemoveFile", "/usr/lib/nim/lib/std/private/osfiles.nim");
	nimln_(352);	result = NIM_TRUE;
	nimln_(365);	{
		NIM_BOOL T3_;
		int T4_;
		T3_ = (NIM_BOOL)0;
		T4_ = (int)0;
		T4_ = unlink(nimToCStringConv(file_p0));
		T3_ = !((T4_ == ((NI32)0)));
		if (!(T3_)) goto LA5_;
		T3_ = !((errno == ((int)2)));
LA5_: ;
		if (!T3_) goto LA6_;
		nimln_(366);		result = NIM_FALSE;
	}
LA6_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, nosremoveFile)(NimStringV2 file_p0) {
NIM_BOOL* nimErr_;
	nimfr_("removeFile", "/usr/lib/nim/lib/std/private/osfiles.nim");
{nimErr_ = nimErrorFlag();
	nimln_(382);	{
		NIM_BOOL T3_;
		NI32 T6_;
		T3_ = (NIM_BOOL)0;
		T3_ = nostryRemoveFile(file_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!!(T3_)) goto LA4_;
		nimln_(383);		T6_ = (NI32)0;
		T6_ = osLastError__stdZoserrors_u122();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		raiseOSError__stdZoserrors_u119(T6_, file_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA4_: ;
	}BeforeRet_: ;
	popFrame();
}
