/* Generated by Nim Compiler v2.2.4 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -pthread   -I/usr/lib/nim/lib -I/home/luminary/Documents/Cybersecurite/Oteria/Venom/ssh_stealer -o /home/luminary/Documents/Cybersecurite/Oteria/Venom/ssh_stealer/sortie_c/@m..@s..@s..@s..@s..@s..@s..@susr@slib@snim@slib@spure@sstrutils.nim.c.o /home/luminary/Documents/Cybersecurite/Oteria/Venom/ssh_stealer/sortie_c/@m..@s..@s..@s..@s..@s..@s..@susr@slib@snim@slib@spure@sstrutils.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
N_NIMCALL(NimStringV2, rawNewString)(NI cap_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1731)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s_p0, NI addLen_p1);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4727)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u14)(NI xX60gensym0__p0);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___system_u2714)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, appendChar)(NimStringV2* dest_p0, NIM_CHAR c_p1);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
extern NIM_THREADVAR TFrame* framePtr__system_u2741;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4509;
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1731)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
{	{
		NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_3;
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		if ((src_p1.len) < ((NI)0) || (src_p1.len) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(src_p1.len, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		copyMem__system_u1731(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		if (nimAddInt((*dest_p0).len, src_p1.len, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_3)) { raiseOverflow(); goto BeforeRet_;
		};
		(*dest_p0).len = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_3);
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
	}BeforeRet_: ;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2741 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2741).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2741;
	framePtr__system_u2741 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4727();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2741 = (*framePtr__system_u2741).prev;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuRepeatStr)(NimStringV2 s_p0, NI n_p1) {
	NimStringV2 result;
	NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_2;
	nimfr_("repeat", "/usr/lib/nim/lib/pure/strutils.nim");
{	result.len = 0; result.p = NIM_NIL;
	nimlf_(1358, "/usr/lib/nim/lib/pure/strutils.nim");	if (nimMulInt(n_p1, s_p0.len, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_2)) { raiseOverflow(); goto BeforeRet_;
	};
	if (((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_2)) < ((NI)0) || ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_2)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_2), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	result = rawNewString(((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_2)));
	{
		NI i_1;
		NI colontmp_;
		NI res_1;
		i_1 = (NI)0;
		colontmp_ = (NI)0;
		nimlf_(81, "/usr/lib/nim/lib/system/iterators_1.nim");		nimlf_(1359, "/usr/lib/nim/lib/pure/strutils.nim");		colontmp_ = n_p1;
		nimlf_(96, "/usr/lib/nim/lib/system/iterators_1.nim");		res_1 = ((NI)1);
		{
			nimln_(97);			while (1) {
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_4;
				if (!(res_1 <= colontmp_)) goto LA3;
				nimlf_(1359, "/usr/lib/nim/lib/pure/strutils.nim");				i_1 = ((NI) (res_1));
				prepareAdd((&result), s_p0.len + 0);
appendString((&result), s_p0);
				nimlf_(102, "/usr/lib/nim/lib/system/iterators_1.nim");				if (nimAddInt(res_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_4)) { raiseOverflow(); goto BeforeRet_;
				};
				res_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_4);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, appendChar)(NimStringV2* dest_p0, NIM_CHAR c_p1) {
	NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_6;
{	(*(*dest_p0).p).data[(*dest_p0).len] = c_p1;
	if (nimAddInt((*dest_p0).len, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_6)) { raiseOverflow(); goto BeforeRet_;
	};
	(*dest_p0).len = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_6);
	(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}BeforeRet_: ;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4509);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuIntToStr)(NI x_p0, NI minchars_p1) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("intToStr", "/usr/lib/nim/lib/pure/strutils.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimlf_(1144, "/usr/lib/nim/lib/pure/strutils.nim");	if (x_p0 == (IL64(-9223372036854775807) - IL64(1))){ raiseOverflow(); goto BeforeRet_;
	}
	result = dollar___systemZdollars_u14((x_p0 > 0? (x_p0) : -(x_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		NI i_1;
		NI colontmp_;
		NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_5;
		NI res_1;
		i_1 = (NI)0;
		colontmp_ = (NI)0;
		nimlf_(81, "/usr/lib/nim/lib/system/iterators_1.nim");		nimlf_(1145, "/usr/lib/nim/lib/pure/strutils.nim");		if (nimSubInt(minchars_p1, result.len, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_5)) { raiseOverflow(); goto BeforeRet_;
		};
		colontmp_ = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_5);
		nimlf_(96, "/usr/lib/nim/lib/system/iterators_1.nim");		res_1 = ((NI)1);
		{
			nimln_(97);			while (1) {
				NimStringV2 T4_;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_7;
				if (!(res_1 <= colontmp_)) goto LA3;
				nimlf_(1145, "/usr/lib/nim/lib/pure/strutils.nim");				i_1 = ((NI) (res_1));
				nimlf_(1694, "/usr/lib/nim/lib/system.nim");				nimlf_(1146, "/usr/lib/nim/lib/pure/strutils.nim");				T4_.len = 0; T4_.p = NIM_NIL;
				T4_ = rawNewString(result.len + 1);
appendChar((&T4_), 48);
appendString((&T4_), result);
				nimlf_(1694, "/usr/lib/nim/lib/system.nim");				eqsink___system_u2714((&result), T4_);
				nimlf_(102, "/usr/lib/nim/lib/system/iterators_1.nim");				if (nimAddInt(res_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_7)) { raiseOverflow(); goto BeforeRet_;
				};
				res_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_7);
			} LA3: ;
		}
	}
	nimlf_(1147, "/usr/lib/nim/lib/pure/strutils.nim");	{
		NimStringV2 T9_;
		if (!(x_p0 < ((NI)0))) goto LA7_;
		nimlf_(1694, "/usr/lib/nim/lib/system.nim");		nimlf_(1148, "/usr/lib/nim/lib/pure/strutils.nim");		T9_.len = 0; T9_.p = NIM_NIL;
		T9_ = rawNewString(result.len + 1);
appendChar((&T9_), 45);
appendString((&T9_), result);
		nimlf_(1694, "/usr/lib/nim/lib/system.nim");		eqsink___system_u2714((&result), T9_);
	}
LA7_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
