/* Generated by Nim Compiler v2.2.4 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -pthread   -I/usr/lib/nim/lib -I/home/luminary/Documents/Cybersecurite/Oteria/Venom/ssh_stealer -o /home/luminary/Documents/Cybersecurite/Oteria/Venom/ssh_stealer/sortie_c/@m..@s..@s..@s..@s..@s..@s..@susr@slib@snim@slib@ssystem@sdollars.nim.c.o /home/luminary/Documents/Cybersecurite/Oteria/Venom/ssh_stealer/sortie_c/@m..@s..@s..@s..@s..@s..@s..@susr@slib@snim@slib@ssystem@sdollars.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyTuple__UV3llMMYFckfui8YMBuUZA tyTuple__UV3llMMYFckfui8YMBuUZA;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tyTuple__UV3llMMYFckfui8YMBuUZA {
	NimStringV2 Field0;
	NimStringV2 Field1;
};
N_LIB_PRIVATE N_NIMCALL(void, addInt__stdZprivateZdigitsutils_u187)(NimStringV2* result_p0, NI64 x_p1);
static N_INLINE(void, addInt__stdZprivateZdigitsutils_u204)(NimStringV2* result_p0, NI x_p1);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4727)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1731)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s_p0, NI addLen_p1);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted__stdZprivateZoscommon_u119)(NimStringV2* s_p0, NimStringV2 x_p1);
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__n49a9aYp5BrbXv9a6OCpJYm0g_2 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_3 = {0, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_2};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_4 = {0, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_2};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__n49a9aYp5BrbXv9a6OCpJYm0g_5 = { 1 | NIM_STRLIT_FLAG, "(" };
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_6 = {1, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_5};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__n49a9aYp5BrbXv9a6OCpJYm0g_7 = { 2 | NIM_STRLIT_FLAG, ", " };
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_8 = {2, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_7};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_10 = {2, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_7};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__n49a9aYp5BrbXv9a6OCpJYm0g_11 = { 1 | NIM_STRLIT_FLAG, "," };
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_12 = {1, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_11};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__n49a9aYp5BrbXv9a6OCpJYm0g_13 = { 1 | NIM_STRLIT_FLAG, ")" };
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_14 = {1, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_13};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_15 = {0, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_2};
extern NIM_THREADVAR TFrame* framePtr__system_u2741;
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2741 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2741).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2741;
	framePtr__system_u2741 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4727();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2741 = (*framePtr__system_u2741).prev;
}
static N_INLINE(void, addInt__stdZprivateZdigitsutils_u204)(NimStringV2* result_p0, NI x_p1) {
	nimfr_("addInt", "/usr/lib/nim/lib/std/private/digitsutils.nim");
	nimlf_(116, "/usr/lib/nim/lib/std/private/digitsutils.nim");	addInt__stdZprivateZdigitsutils_u187(result_p0, ((NI64) (x_p1)));
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u14)(NI xX60gensym0__p0) {
	NimStringV2 result;
	nimfr_("$", "/usr/lib/nim/lib/system/dollars.nim");
	nimlf_(20, "/usr/lib/nim/lib/system/dollars.nim");	result = TM__n49a9aYp5BrbXv9a6OCpJYm0g_4;
	nimln_(21);	addInt__stdZprivateZdigitsutils_u204((&result), xX60gensym0__p0);
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u34)(NI64 xX60gensym4__p0) {
	NimStringV2 result;
	nimfr_("$", "/usr/lib/nim/lib/system/dollars.nim");
	nimln_(20);	result = TM__n49a9aYp5BrbXv9a6OCpJYm0g_3;
	nimln_(21);	addInt__stdZprivateZdigitsutils_u187((&result), xX60gensym4__p0);
	popFrame();
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1731)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
{	{
		NI TM__n49a9aYp5BrbXv9a6OCpJYm0g_9;
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		if ((src_p1.len) < ((NI)0) || (src_p1.len) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(src_p1.len, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		copyMem__system_u1731(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		if (nimAddInt((*dest_p0).len, src_p1.len, &TM__n49a9aYp5BrbXv9a6OCpJYm0g_9)) { raiseOverflow(); goto BeforeRet_;
		};
		(*dest_p0).len = (NI)(TM__n49a9aYp5BrbXv9a6OCpJYm0g_9);
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___stdZprivateZoscommon_u93)(tyTuple__UV3llMMYFckfui8YMBuUZA* x_p0) {
	NimStringV2 result;
	NI countX60gensym3__1;
	nimfr_("$", "/usr/lib/nim/lib/system/dollars.nim");
	nimln_(94);	nimlf_(19, "/usr/lib/nim/lib/std/private/miscdollars.nim");	result = TM__n49a9aYp5BrbXv9a6OCpJYm0g_6;
	nimln_(21);	countX60gensym3__1 = ((NI)0);
	{
		if (!NIM_TRUE) goto LA3_;
		nimln_(23);		{
			if (!(((NI)0) < countX60gensym3__1)) goto LA7_;
			prepareAdd((&result), 2);
appendString((&result), TM__n49a9aYp5BrbXv9a6OCpJYm0g_8);
		}
LA7_: ;
		nimln_(27);		countX60gensym3__1 += ((NI)1);
		nimln_(33);		addQuoted__stdZprivateZoscommon_u119((&result), (*x_p0).Field0);
	}
LA3_: ;
	{
		if (!NIM_TRUE) goto LA11_;
		nimln_(23);		{
			if (!(((NI)0) < countX60gensym3__1)) goto LA15_;
			prepareAdd((&result), 2);
appendString((&result), TM__n49a9aYp5BrbXv9a6OCpJYm0g_10);
		}
LA15_: ;
		nimln_(27);		countX60gensym3__1 += ((NI)1);
		nimln_(33);		addQuoted__stdZprivateZoscommon_u119((&result), (*x_p0).Field1);
	}
LA11_: ;
	nimln_(37);	{
		if (!(countX60gensym3__1 == ((NI)1))) goto LA19_;
		nimln_(38);		prepareAdd((&result), 1);
appendString((&result), TM__n49a9aYp5BrbXv9a6OCpJYm0g_12);
	}
LA19_: ;
	nimln_(39);	prepareAdd((&result), 1);
appendString((&result), TM__n49a9aYp5BrbXv9a6OCpJYm0g_14);
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u29)(NI32 xX60gensym3__p0) {
	NimStringV2 result;
	nimfr_("$", "/usr/lib/nim/lib/system/dollars.nim");
	nimlf_(20, "/usr/lib/nim/lib/system/dollars.nim");	result = TM__n49a9aYp5BrbXv9a6OCpJYm0g_15;
	nimln_(21);	addInt__stdZprivateZdigitsutils_u204((&result), ((NI) (xX60gensym3__p0)));
	popFrame();
	return result;
}
