/* Generated by Nim Compiler v2.2.4 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -pthread   -I/usr/lib/nim/lib -I/home/luminary/Documents/Cybersecurite/Oteria/Venom/ssh_stealer -o /home/luminary/Documents/Cybersecurite/Oteria/Venom/ssh_stealer/sortie_c/@m..@s..@s..@s..@s..@s..@s..@susr@slib@snim@slib@ssystem@sexceptions.nim.c.o /home/luminary/Documents/Cybersecurite/Oteria/Venom/ssh_stealer/sortie_c/@m..@s..@s..@s..@s..@s..@s..@susr@slib@snim@slib@ssystem@sexceptions.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tyObject_OverflowDefect__bWTIRLTSZh6zcYQtQGa0gw tyObject_OverflowDefect__bWTIRLTSZh6zcYQtQGa0gw;
typedef struct tyObject_RefHeader__ZRImJ0JOtQAFc4hlgAu5tA tyObject_RefHeader__ZRImJ0JOtQAFc4hlgAu5tA;
typedef struct tyObject_ArithmeticDefect__z8t9brvllLV9bkj4dPdz270g tyObject_ArithmeticDefect__z8t9brvllLV9bkj4dPdz270g;
typedef struct tyObject_Defect__bs0znt1OsCtQtCP6xcUHbg tyObject_Defect__bs0znt1OsCtQtCP6xcUHbg;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ;
typedef struct tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ_Content tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ_Content;
typedef struct tyObject_GcEnv__bKm2paCpAI9b9cmSEWTeAkXA tyObject_GcEnv__bKm2paCpAI9b9cmSEWTeAkXA;
typedef struct tyObject_CellSeq__85msh6dF3B9bm1Xv9cjHSiuw tyObject_CellSeq__85msh6dF3B9bm1Xv9cjHSiuw;
typedef struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q tyTuple__N4J9cV4JZGem3ljqqj5rT0Q;
typedef struct tyObject_CellSeq__5ocgJVj73q9aR2AYeInENfQ tyObject_CellSeq__5ocgJVj73q9aR2AYeInENfQ;
typedef struct tyTuple__RZEZlyko4VRjsGRM9bCskqQ tyTuple__RZEZlyko4VRjsGRM9bCskqQ;
typedef struct tyObject_RangeDefect__f8Gz09bFBpVdOfWnWULhUJQ tyObject_RangeDefect__f8Gz09bFBpVdOfWnWULhUJQ;
typedef struct tyObject_IndexDefect__sElvOV9bPt9cEiWsJhV2j88w tyObject_IndexDefect__sElvOV9bPt9cEiWsJhV2j88w;
typedef struct tyObject_AssertionDefect__5NaWWiRQbiFVJRYW9aFXCOA tyObject_AssertionDefect__5NaWWiRQbiFVJRYW9aFXCOA;
typedef struct tyObject_OSError__vXAAlvrJPOVadDkbOWUyiA tyObject_OSError__vXAAlvrJPOVadDkbOWUyiA;
typedef struct tyObject_CatchableError__9ab9cPq83jNmwEkPYefdrBpg tyObject_CatchableError__9ab9cPq83jNmwEkPYefdrBpg;
typedef struct tyObject_IOError__Vn1F4tzy8Snk2yXd61F9cQA tyObject_IOError__Vn1F4tzy8Snk2yXd61F9cQA;
typedef struct tyObject_DivByZeroDefect__wPoPB2T8S4MvWgMnsz6uvw tyObject_DivByZeroDefect__wPoPB2T8S4MvWgMnsz6uvw;
typedef struct tyObject_StackTraceEntry__Ys9cmA3ckZAVfrZgZt9axXEw tyObject_StackTraceEntry__Ys9cmA3ckZAVfrZgZt9axXEw;
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct tyObject_RefHeader__ZRImJ0JOtQAFc4hlgAu5tA {
	NI rc;
	NI rootIdx;
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ {
  NI len; tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ trace;
	Exception* up;
};
struct tyObject_Defect__bs0znt1OsCtQtCP6xcUHbg {
	Exception Sup;
};
struct tyObject_ArithmeticDefect__z8t9brvllLV9bkj4dPdz270g {
	tyObject_Defect__bs0znt1OsCtQtCP6xcUHbg Sup;
};
struct tyObject_OverflowDefect__bWTIRLTSZh6zcYQtQGa0gw {
	tyObject_ArithmeticDefect__z8t9brvllLV9bkj4dPdz270g Sup;
};
struct tyObject_CellSeq__85msh6dF3B9bm1Xv9cjHSiuw {
	NI len;
	NI cap;
	tyTuple__N4J9cV4JZGem3ljqqj5rT0Q* d;
};
struct tyObject_CellSeq__5ocgJVj73q9aR2AYeInENfQ {
	NI len;
	NI cap;
	tyTuple__RZEZlyko4VRjsGRM9bCskqQ* d;
};
struct tyObject_GcEnv__bKm2paCpAI9b9cmSEWTeAkXA {
	tyObject_CellSeq__85msh6dF3B9bm1Xv9cjHSiuw traceStack;
	tyObject_CellSeq__5ocgJVj73q9aR2AYeInENfQ toFree;
	NI freed;
	NI touched;
	NI edges;
	NI rcSum;
	NIM_BOOL keepThreshold;
};
struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q {
	void** Field0;
	TNimTypeV2* Field1;
};
struct tyObject_RangeDefect__f8Gz09bFBpVdOfWnWULhUJQ {
	tyObject_Defect__bs0znt1OsCtQtCP6xcUHbg Sup;
};
struct tyObject_IndexDefect__sElvOV9bPt9cEiWsJhV2j88w {
	tyObject_Defect__bs0znt1OsCtQtCP6xcUHbg Sup;
};
struct tyObject_AssertionDefect__5NaWWiRQbiFVJRYW9aFXCOA {
	tyObject_Defect__bs0znt1OsCtQtCP6xcUHbg Sup;
};
struct tyObject_CatchableError__9ab9cPq83jNmwEkPYefdrBpg {
	Exception Sup;
};
struct tyObject_OSError__vXAAlvrJPOVadDkbOWUyiA {
	tyObject_CatchableError__9ab9cPq83jNmwEkPYefdrBpg Sup;
	NI32 errorCode;
};
struct tyObject_IOError__Vn1F4tzy8Snk2yXd61F9cQA {
	tyObject_CatchableError__9ab9cPq83jNmwEkPYefdrBpg Sup;
};
struct tyObject_DivByZeroDefect__wPoPB2T8S4MvWgMnsz6uvw {
	tyObject_ArithmeticDefect__z8t9brvllLV9bkj4dPdz270g Sup;
};
struct tyObject_StackTraceEntry__Ys9cmA3ckZAVfrZgZt9axXEw {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ_Content { NI cap; tyObject_StackTraceEntry__Ys9cmA3ckZAVfrZgZt9axXEw data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u56)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u5266)(tyObject_OverflowDefect__bWTIRLTSZh6zcYQtQGa0gw* dest_p0);
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0);
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4727)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, rememberCycle__system_u3546)(NIM_BOOL isDestroyAction_p0, tyObject_RefHeader__ZRImJ0JOtQAFc4hlgAu5tA* s_p1, TNimTypeV2* desc_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZassertions_u74)(tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u5278)(tyObject_OverflowDefect__bWTIRLTSZh6zcYQtQGa0gw* dest_p0, void* env_p1);
static N_INLINE(void, nimTraceRefDyn)(void* q_p0, void* env_p1);
static N_INLINE(void, add__system_u3029)(tyObject_CellSeq__85msh6dF3B9bm1Xv9cjHSiuw* s_p0, void** c_p1, TNimTypeV2* t_p2);
N_LIB_PRIVATE N_NIMCALL(void, resize__system_u3037)(tyObject_CellSeq__85msh6dF3B9bm1Xv9cjHSiuw* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u60)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4793)(tyObject_RangeDefect__f8Gz09bFBpVdOfWnWULhUJQ* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u4805)(tyObject_RangeDefect__f8Gz09bFBpVdOfWnWULhUJQ* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u62)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4862)(tyObject_IndexDefect__sElvOV9bPt9cEiWsJhV2j88w* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u4874)(tyObject_IndexDefect__sElvOV9bPt9cEiWsJhV2j88w* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u64)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZassertions_u35)(tyObject_AssertionDefect__5NaWWiRQbiFVJRYW9aFXCOA* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___stdZassertions_u47)(tyObject_AssertionDefect__5NaWWiRQbiFVJRYW9aFXCOA* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u66)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZoserrors_u60)(tyObject_OSError__vXAAlvrJPOVadDkbOWUyiA* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___stdZoserrors_u72)(tyObject_OSError__vXAAlvrJPOVadDkbOWUyiA* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u68)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u9033)(tyObject_IOError__Vn1F4tzy8Snk2yXd61F9cQA* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u9045)(tyObject_IOError__Vn1F4tzy8Snk2yXd61F9cQA* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u70)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u5332)(tyObject_DivByZeroDefect__wPoPB2T8S4MvWgMnsz6uvw* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u5344)(tyObject_DivByZeroDefect__wPoPB2T8S4MvWgMnsz6uvw* dest_p0, void* env_p1);
N_LIB_PRIVATE TNimTypeV2 NTIv2__bWTIRLTSZh6zcYQtQGa0gw_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__f8Gz09bFBpVdOfWnWULhUJQ_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__sElvOV9bPt9cEiWsJhV2j88w_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__5NaWWiRQbiFVJRYW9aFXCOA_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__vXAAlvrJPOVadDkbOWUyiA_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__Vn1F4tzy8Snk2yXd61F9cQA_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__wPoPB2T8S4MvWgMnsz6uvw_;
extern NIM_THREADVAR TFrame* framePtr__system_u2741;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4509;
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_3[5] = {3701606400, 1285336064, 3442712064, 3414076928, 1690846208};
N_LIB_PRIVATE TNimTypeV2 NTIv2__bWTIRLTSZh6zcYQtQGa0gw_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u56, .size = sizeof(tyObject_OverflowDefect__bWTIRLTSZh6zcYQtQGa0gw), .align = (NI16) NIM_ALIGNOF(tyObject_OverflowDefect__bWTIRLTSZh6zcYQtQGa0gw), .depth = 4, .display = TM__TzI3paKQY09cLjc9cmCvur3A_3, .traceImpl = (void*)eqtrace___system_u5278, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_5[4] = {3701606400, 1285336064, 3442712064, 3249787648};
N_LIB_PRIVATE TNimTypeV2 NTIv2__f8Gz09bFBpVdOfWnWULhUJQ_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u60, .size = sizeof(tyObject_RangeDefect__f8Gz09bFBpVdOfWnWULhUJQ), .align = (NI16) NIM_ALIGNOF(tyObject_RangeDefect__f8Gz09bFBpVdOfWnWULhUJQ), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_5, .traceImpl = (void*)eqtrace___system_u4805, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_6[4] = {3701606400, 1285336064, 3442712064, 1232025856};
N_LIB_PRIVATE TNimTypeV2 NTIv2__sElvOV9bPt9cEiWsJhV2j88w_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u62, .size = sizeof(tyObject_IndexDefect__sElvOV9bPt9cEiWsJhV2j88w), .align = (NI16) NIM_ALIGNOF(tyObject_IndexDefect__sElvOV9bPt9cEiWsJhV2j88w), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_6, .traceImpl = (void*)eqtrace___system_u4874, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_7[4] = {3701606400, 1285336064, 3442712064, 3600177664};
N_LIB_PRIVATE TNimTypeV2 NTIv2__5NaWWiRQbiFVJRYW9aFXCOA_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u64, .size = sizeof(tyObject_AssertionDefect__5NaWWiRQbiFVJRYW9aFXCOA), .align = (NI16) NIM_ALIGNOF(tyObject_AssertionDefect__5NaWWiRQbiFVJRYW9aFXCOA), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_7, .traceImpl = (void*)eqtrace___stdZassertions_u47, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_8[4] = {3701606400, 1285336064, 3218057984, 1879086592};
N_LIB_PRIVATE TNimTypeV2 NTIv2__vXAAlvrJPOVadDkbOWUyiA_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u66, .size = sizeof(tyObject_OSError__vXAAlvrJPOVadDkbOWUyiA), .align = (NI16) NIM_ALIGNOF(tyObject_OSError__vXAAlvrJPOVadDkbOWUyiA), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_8, .traceImpl = (void*)eqtrace___stdZoserrors_u72, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_9[4] = {3701606400, 1285336064, 3218057984, 2101731840};
N_LIB_PRIVATE TNimTypeV2 NTIv2__Vn1F4tzy8Snk2yXd61F9cQA_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u68, .size = sizeof(tyObject_IOError__Vn1F4tzy8Snk2yXd61F9cQA), .align = (NI16) NIM_ALIGNOF(tyObject_IOError__Vn1F4tzy8Snk2yXd61F9cQA), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_9, .traceImpl = (void*)eqtrace___system_u9045, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_10[5] = {3701606400, 1285336064, 3442712064, 3414076928, 4195288832};
N_LIB_PRIVATE TNimTypeV2 NTIv2__wPoPB2T8S4MvWgMnsz6uvw_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u70, .size = sizeof(tyObject_DivByZeroDefect__wPoPB2T8S4MvWgMnsz6uvw), .align = (NI16) NIM_ALIGNOF(tyObject_DivByZeroDefect__wPoPB2T8S4MvWgMnsz6uvw), .depth = 4, .display = TM__TzI3paKQY09cLjc9cmCvur3A_10, .traceImpl = (void*)eqtrace___system_u5344, .flags = 0};
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2741 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2741).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2741;
	framePtr__system_u2741 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4727();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2741 = (*framePtr__system_u2741).prev;
}
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1) {
	NI result;
	nimfr_("-%", "/usr/lib/nim/lib/system/arithmetics.nim");
	nimlf_(364, "/usr/lib/nim/lib/system/arithmetics.nim");	nimln_(368);	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) - (NU64)(((NU) (y_p1))))));
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4509);
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0) {
	NIM_BOOL result;
NIM_BOOL* nimErr_;
	nimfr_("nimDecRefIsLastCyclicDyn", "/usr/lib/nim/lib/system/orc.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(512, "/usr/lib/nim/lib/system/orc.nim");	result = NIM_FALSE;
	nimln_(513);	{
		tyObject_RefHeader__ZRImJ0JOtQAFc4hlgAu5tA* cell_1;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		nimln_(514);		nimlf_(58, "/usr/lib/nim/lib/system/arc.nim");		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
		cell_1 = ((tyObject_RefHeader__ZRImJ0JOtQAFc4hlgAu5tA*) (T5_));
		nimlf_(515, "/usr/lib/nim/lib/system/orc.nim");		{
			if (!((NI)((*cell_1).rc & ((NI)-16)) == ((NI)0))) goto LA8_;
			nimln_(516);			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			NI TM__TzI3paKQY09cLjc9cmCvur3A_2;
			nimln_(519);			if (nimSubInt((*cell_1).rc, ((NI)16), &TM__TzI3paKQY09cLjc9cmCvur3A_2)) { raiseOverflow(); goto BeforeRet_;
			};
			(*cell_1).rc = (NI)(TM__TzI3paKQY09cLjc9cmCvur3A_2);
		}
LA6_: ;
		nimln_(521);		rememberCycle__system_u3546(result, cell_1, (*((TNimTypeV2**) (p_p0))));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA3_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u5266)(tyObject_OverflowDefect__bWTIRLTSZh6zcYQtQGa0gw* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.parent);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.parent);
	}
LA4_: ;
	if ((*dest_p0).Sup.Sup.Sup.message.p && !((*dest_p0).Sup.Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.Sup.message.p);
}
	eqdestroy___stdZassertions_u74((*dest_p0).Sup.Sup.Sup.trace);
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.up);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.up);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u56)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___system_u5266(((tyObject_OverflowDefect__bWTIRLTSZh6zcYQtQGa0gw*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, add__system_u3029)(tyObject_CellSeq__85msh6dF3B9bm1Xv9cjHSiuw* s_p0, void** c_p1, TNimTypeV2* t_p2) {
	void** colontmp_;
	TNimTypeV2* colontmp__2;
	NI TM__TzI3paKQY09cLjc9cmCvur3A_4;
	nimfr_("add", "/usr/lib/nim/lib/system/cellseqs_v2.nim");
{	nimlf_(28, "/usr/lib/nim/lib/system/cellseqs_v2.nim");	{
		if (!((*s_p0).cap <= (*s_p0).len)) goto LA3_;
		nimln_(29);		resize__system_u3037(s_p0);
	}
LA3_: ;
	nimln_(30);	colontmp_ = c_p1;
	colontmp__2 = t_p2;
	(*s_p0).d[(*s_p0).len].Field0 = colontmp_;
	(*s_p0).d[(*s_p0).len].Field1 = colontmp__2;
	nimln_(31);	if (nimAddInt((*s_p0).len, ((NI)1), &TM__TzI3paKQY09cLjc9cmCvur3A_4)) { raiseOverflow(); goto BeforeRet_;
	};
	(*s_p0).len = (NI)(TM__TzI3paKQY09cLjc9cmCvur3A_4);
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(void, nimTraceRefDyn)(void* q_p0, void* env_p1) {
	void** p_1;
	nimfr_("nimTraceRefDyn", "/usr/lib/nim/lib/system/orc.nim");
	nimlf_(136, "/usr/lib/nim/lib/system/orc.nim");	p_1 = ((void**) (q_p0));
	nimln_(137);	{
		tyObject_GcEnv__bKm2paCpAI9b9cmSEWTeAkXA* j_1;
		if (!!(((*p_1) == NIM_NIL))) goto LA3_;
		nimln_(138);		j_1 = ((tyObject_GcEnv__bKm2paCpAI9b9cmSEWTeAkXA*) (env_p1));
		nimln_(139);		add__system_u3029((&(*j_1).traceStack), p_1, (*((TNimTypeV2**) ((*p_1)))));
	}
LA3_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u5278)(tyObject_OverflowDefect__bWTIRLTSZh6zcYQtQGa0gw* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4793)(tyObject_RangeDefect__f8Gz09bFBpVdOfWnWULhUJQ* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA4_: ;
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	eqdestroy___stdZassertions_u74((*dest_p0).Sup.Sup.trace);
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u60)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___system_u4793(((tyObject_RangeDefect__f8Gz09bFBpVdOfWnWULhUJQ*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u4805)(tyObject_RangeDefect__f8Gz09bFBpVdOfWnWULhUJQ* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4862)(tyObject_IndexDefect__sElvOV9bPt9cEiWsJhV2j88w* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA4_: ;
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	eqdestroy___stdZassertions_u74((*dest_p0).Sup.Sup.trace);
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u62)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___system_u4862(((tyObject_IndexDefect__sElvOV9bPt9cEiWsJhV2j88w*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u4874)(tyObject_IndexDefect__sElvOV9bPt9cEiWsJhV2j88w* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZassertions_u35)(tyObject_AssertionDefect__5NaWWiRQbiFVJRYW9aFXCOA* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA4_: ;
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	eqdestroy___stdZassertions_u74((*dest_p0).Sup.Sup.trace);
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u64)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___stdZassertions_u35(((tyObject_AssertionDefect__5NaWWiRQbiFVJRYW9aFXCOA*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___stdZassertions_u47)(tyObject_AssertionDefect__5NaWWiRQbiFVJRYW9aFXCOA* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZoserrors_u60)(tyObject_OSError__vXAAlvrJPOVadDkbOWUyiA* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA4_: ;
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	eqdestroy___stdZassertions_u74((*dest_p0).Sup.Sup.trace);
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u66)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___stdZoserrors_u60(((tyObject_OSError__vXAAlvrJPOVadDkbOWUyiA*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___stdZoserrors_u72)(tyObject_OSError__vXAAlvrJPOVadDkbOWUyiA* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u9033)(tyObject_IOError__Vn1F4tzy8Snk2yXd61F9cQA* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA4_: ;
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	eqdestroy___stdZassertions_u74((*dest_p0).Sup.Sup.trace);
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u68)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___system_u9033(((tyObject_IOError__Vn1F4tzy8Snk2yXd61F9cQA*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u9045)(tyObject_IOError__Vn1F4tzy8Snk2yXd61F9cQA* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u5332)(tyObject_DivByZeroDefect__wPoPB2T8S4MvWgMnsz6uvw* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.parent);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.parent);
	}
LA4_: ;
	if ((*dest_p0).Sup.Sup.Sup.message.p && !((*dest_p0).Sup.Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.Sup.message.p);
}
	eqdestroy___stdZassertions_u74((*dest_p0).Sup.Sup.Sup.trace);
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.up);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.up);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u70)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___system_u5332(((tyObject_DivByZeroDefect__wPoPB2T8S4MvWgMnsz6uvw*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u5344)(tyObject_DivByZeroDefect__wPoPB2T8S4MvWgMnsz6uvw* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.Sup.up, env_p1);
}
